### ISSUE TITLE
Cannot run the gfx_advanced example with_multisampling : thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat'

### ISSUE THREAD

**Issue by o0Ignition0o** [nical/lyon#116]
Tried to run the gfx_advanced example on my Arch linux laptop, and it crashed during the "gfx_window_glutin::init" call.

I've done a bit of heuristics since I was able to run the gfx_basic example, and it turns out I'm able to run the example as long as the ".with_multisampling(8)"  part of the glutin::WindowBuilder::new() method is commented out : 

`     // Initialize glutin and gfx-rs (refer to gfx-rs examples for more details).

    let glutin_builder = glutin::WindowBuilder::new()
        .with_dimensions(700, 700)
        .with_decorations(true)
        .with_title("tessellation".to_string())
        //.with_multisampling(8) // This line causes a crash
        .with_vsync();   `

Currently using my Intel graphics card "VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)" (I have no idea if it's any use).

Here is a report of the rust backtrace : 

` 
gfx_advanced git:(master) ✗ export RUST_BACKTRACE=1; cargo run
   Compiling gfx-rs advanced example v0.1.0 (file:///home/ignition/Documents/Projects/rust/lyon/examples/gfx_advanced)
warning: unused import: `DepthStencil`
  --> src/main.rs:29:24
   |
29 | use gfx_core::format::{DepthStencil, Rgba8};
   |                        ^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 3.48 secs
     Running `/home/ignition/Documents/Projects/rust/lyon/target/debug/gfx_advanced`
== gfx-rs example ==
Controls:
  Arrow keys: scrolling
  PgUp/PgDown: zoom in/out
  w: toggle wireframe mode
  p: toggle showing points
  b: toggle drawing the background
  a/z: increase/decrease the stroke width
 -- fill: 460 vertices 1416 indices
 -- stroke: 1292 vertices 3816 indices
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: gfx_window_glutin::init_raw
             at /home/ignition/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.14.0/src/lib.rs:101
  12: gfx_window_glutin::init
             at /home/ignition/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.14.0/src/lib.rs:53
  13: gfx_advanced::main
             at ./src/main.rs:257
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  16: main
  17: __libc_start_main
  18: _start
  `
I'd love to dig into it a bit more, but I feel kind of lost ^^

**Comment by nical** [comment]
Huh! Let's just remove that line. Multisampling is not important for the sake of the example and if it prevents the example from running on some people's computers then it brings more bad than good.

**Comment by nical** [comment]
Oh, and thanks for figuring this out! I wonder if it is the same problem as #29.

**Comment by o0Ignition0o** [comment]
I'll make a pr and ask @tioover if it works ! :)
