### ISSUE TITLE
Add ellipses back to the basic_shapes tessellators

### ISSUE THREAD

**Issue by nical** [nical/lyon#125]
Having ellipses would be useful for [ggez](https://github.com/ggez/ggez/). The API should have the subdivision computed in function of a tolerance threshold like all of the other tessellators, and maybe have a rotation parameter (equivalent to the `x_rotation` in arcs).

**Comment by icefoxen** [comment]
I'd be happy to contribute this if I find time and can figure out lyon's infrastructure enough to implement the algorithm.  (And figure out how the tolerance threshold works.)

**Comment by nical** [comment]
I have this implemented on a computer I'll have access to tomorrow (forgot to push!).
