### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by icefoxen** [nical/lyon#127]
On https://docs.rs/lyon/0.7.0/lyon/tessellation/index.html , under "Overview":

```
The most interesting modules of this crate are:

    path_fill - Implementing the tessellation of complex path fill operations.
    path_stroke - Implementing the tessellation of complex path stroke operations.
    geometry_builder - Which the above two are built on. It provides traits to facilitate generating arbitrary vertex and index buffers.
```

The `path_fill` and `path_stroke` module links are dead and I can't find them in a cursory search of the docs; are they old stuff that's been removed?

**Comment by nical** [comment]
Oops! I stopped exposing the path_fill and path_stroke modules (relevant symbols are reexported at the root of the lyon_tessellation crate), so the module docs went away in the process. I'll look into whether there was a lot in the module doc or if it can be inlined directly in the docs of FillTessellator and StrokeTessellator.
