### ISSUE TITLE
Document the meaning of the "tolerance" parameter of the circle and rounded_rectangle builder functions

### ISSUE THREAD

**Issue by icefoxen** [nical/lyon#128]
It appears to be the maximum departure from the true radius that the circle-approximator will allow.  Still not sure if it's normalized to the size of the circle or not.

Will probably make a PR for this when I have time.

**Comment by nical** [comment]
Thanks for filing this. Tolerance is described in [the lyon_bezier doc](https://docs.rs/lyon_bezier/0.7.0/lyon_bezier/#flattening). We need to link to it in the many other places where the terms shows up.

**Comment by nical** [comment]
All occurences of the tolerance parameter link to the explaination in the `lyon_geom` doc as far as I know.
