### ISSUE TITLE
Make the basic_shapes tessellation routines provide vertex normals

### ISSUE THREAD

**Issue by nical** [nical/lyon#13]
The GeometryBuilder trait can take an optional normal argument in add_vertex. Currently, none of the simple tessellation routines in [basic_shapes.rs](https://github.com/nical/lyon/blob/inbound/tessellation/src/basic_shapes.rs) provide the normals even though it is pretty easy to implement.

**Comment by nical** [comment]
Current status:

- [x] fill_triangle
- [x] stroke_triangle
- [x] fill_quad
- [x] stroke_quad
- [x] fill_rectangle
- [x] stroke_rectangle
- [ ] fill_ellipse
- [ ] stroke_ellipse (missing)
- [ ] fill_convex_polyline
- [x] stroke_polyline

**Comment by kuxv** [comment]
Hi, I will have a look on this.

**Comment by nical** [comment]
@kuxv Great! Don't hesitate to let me know if there is anything I can do to help you get started.

**Comment by kuxv** [comment]
I think I have good idea of what needs to be done for fill_convex_polyline().
The normal of any inner point on line should be calculated from it's surrounding edges, i.e. if I have a line of 3 points A,B,C then the normal in B is calculated from edges B-A, C-B. Is that correct @nical ? If yes I have 2 questions:
1) Normals in the edge points, first and last. Should they be calculated from the edges of triangle they are part of?
2) Is the number of input points arbitrary? If it is less than 3 then again I am not sure about the normals of a line(there is more than one solution, right? ;)

**Comment by nical** [comment]
> the normal in B is calculated from edges B-A, C-B. Is that correct @nical ? If yes I have 2 questions:

Correct.

>    Normals in the edge points, first and last. Should they be calculated from the edges of triangle they are part of?

The first point has an edge that comes from the last point and an edge that goes to the second point, so it should use these two edges to calculate the normal. The last point has an edge from the previous point and an edge to the first point.

(I hope this doesn't make things more confusing)

>    Is the number of input points arbitrary? If it is less than 3 then again I am not sure about the normals of a line(there is more than one solution, right? ;)

The number of points is arbitrary, but if it is less than three we can just early-return since there is not area to fill.

**Comment by kuxv** [comment]
It seems the normal calculation is already done for stroke_border_radius. So the only missing was fill_convex_polyline and that should be fixed by #81?

**Comment by nical** [comment]
@kuxv Correct. Looks like we can close this as soon as #81 is merged.
