### ISSUE TITLE
Types should impl Clone and Debug when possible

### ISSUE THREAD

**Issue by icefoxen** [nical/lyon#167]
`lyon::tessellation::VertexBuffers` is what I originally noticed lacking this, though there's probably others.

This lack makes it impossible to derive Debug or Clone on types containing this, such as a mesh builder that contains the buffer for you.

**Comment by nical** [comment]
#169 added Clone and Debug impl for VertexBuffers, don't hesitate to open new issues if you come across other missing trait impls.
