### ISSUE TITLE
StrokeBuilder is numerically unstable for consecutive Bezier curves

### ISSUE THREAD

**Issue by pizzaiter** [nical/lyon#184]
Here is an example to illustrate the problem.

```rust
extern crate lyon;

use lyon::tessellation::{VertexBuffers, StrokeOptions, StrokeBuilder};
use lyon::tessellation::geometry_builder::simple_builder;
use lyon::math::point;
use lyon::path_builder::{FlatPathBuilder, PathBuilder};

fn main() {
    let a = point(-300.0, -100.0);
    let b = point(-300.0, 0.0);
    let c = point(39.87738037109375, -105.883056640625);
    let d = point(-300.0, -200.0);

    let mut buffers = VertexBuffers::new();
    {
        let mut output = simple_builder(&mut buffers);
        let mut builder = StrokeBuilder::new(&StrokeOptions::default(), &mut output);

        builder.move_to(a);
        builder.cubic_bezier_to(b, c, c);
        builder.cubic_bezier_to(c, d, a);
        builder.build();
    }
    println!("{}", buffers.vertices.len()); // 54

    let mut buffers = VertexBuffers::new();
    {
        let mut output = simple_builder(&mut buffers);
        let mut builder = StrokeBuilder::new(&StrokeOptions::default(), &mut output);

        // only the first segment
        builder.move_to(a);
        builder.cubic_bezier_to(b, c, c);
        builder.build();
    }
    println!("{}", buffers.vertices.len()); // 52

    let mut buffers = VertexBuffers::new();
    {
        let mut output = simple_builder(&mut buffers);
        let mut builder = StrokeBuilder::new(&StrokeOptions::default(), &mut output);

        // only the second segment
        builder.move_to(c);
        builder.cubic_bezier_to(c, d, a);
        builder.build();
    }
    println!("{}", buffers.vertices.len()); // 48
}
```

The example tessellates two Bezier segments, where the second one is essentially just the first one mirrored on the x-axis. So both segments should generate roughly the same amount of vertices. When one tessellates each individually this is in fact the case. However, tessellating one after the other results in only 2 additional vertices generated by the second segment, effectively tessellating it into a single straight line.

Note that the control points around `c` are supposed to be exactly equal to `c`.

I investigated and think the problem results from a combination of two things:

- `edge_to` ignores short edges. In the example this leads to the situation that the current position after the first segment is not exactly `c`.

- `flatten_cubic_bezier` seems to be unstable, when `ctrl1` is very close to but unequal to `from`.

More specifically, I think the following check in `no_inflection_flattening_step` is overly conservative.

```rust
if (v2_cross_v1 * h).abs() < 1e-5 {
    return 1.0;
}
```

Maybe it would be better to check if `s2inv` (or `t`) is NaN instead? I could make a PR with this change.

**Comment by nical** [comment]
Hi @pizzaiter, thanks a lot for filing this! A lot of the constant thresholds are a bit arbitrary so I wouldn't be surprised that some of them are too (or not enough) conservative, as you said.
You are also right about the edge_to bug.

I'll have a closer look very soon and get back to you.

**Comment by nical** [comment]
So, for `edge_to`, I think that we should just ignore points if they are strictly equal to the previous point instead of having a threshold on the length.

For the code in `no_inflection_flattening_step` using strict equality with zero should work as well (I have slight preference towards this rather than checking for NaN unless you feel strongly otherwise).

If you want to make a PR I'll happily take it, after all it's fair to give credit in the git history where it's due.
If you'd prefer me to do it let me know.

**Comment by pizzaiter** [comment]
Sounds good! I made a PR.
