### ISSUE TITLE
Consider moving everything to the MPL2 license.

### ISSUE THREAD

**Issue by nical** [nical/lyon#244]
MLP2 is a very permissive license. Not quite as permissive as MIT+Apache, but still very permissive. In a nutshell, the code can be used at will, including in closed source software, but modifications to the code must be made public.
In my opinion this is a fair deal because people can use your work for free, and if they improve upon it, these improvements must be shared which encourages open innovation without forcing you to open *all* of your code like the GPL would.

The other motivation for moving to MPL2 is to facilitate sharing code with [PathFinder](https://github.com/pcwalton/pathfinder) which is licensed under MPL2.

More about the MPL2 license: https://www.mozilla.org/en-US/MPL/2.0/

Edit: Turns out I confused Pathfinder's license with another project, the former being under MIT/Apache2. So the decision is to remain MIT/Apache2 for now, but leave the door open for changing this in the future.

**Comment by nical** [comment]
To change the license I believe I need the approval of the (awesome) individuals who contributed code:

- [ ] @UrbanSolution
- [ ] @RazrFalcon
- [ ] @o0Ignition0o
- [ ] @emilio
- [ ] @icefoxen
- [ ] @jaemk
- [ ] @dowoncha
- [ ] @nivkner
- [ ] @kuxv
- [ ] @kaedroho
- [ ] @Noxivs
- [ ] @anna-liao
- [ ] @EloD10
- [ ] @pizzaiter
- [ ] @whmountains
- [ ] @bostelk

Apologies for the spam. If you are in this list please let me know in this thread if you agree to change the license of your contribution from MIT + Apache v2 to MPL v2.0. Don't hesitate to voice any concern.

**Comment by kuxv** [comment]
No problem.

**Comment by bostelk** [comment]
I agree.

**Comment by RazrFalcon** [comment]
I'm fine.

**Comment by whmountains** [comment]
I approve of this change.  Go ahead.

**Comment by EloD10** [comment]
It's awesome! #pathfinder

**Comment by dowoncha** [comment]
You have my go.

**Comment by kaedroho** [comment]
Fine by me, thanks for asking!

**Comment by anna-liao** [comment]
I agree :+1:

**Comment by jaemk** [comment]
I agree

**Comment by nivkner** [comment]
I agree

**Comment by UrbanSolution** [comment]
I agree !

Thomas Sajot

**Comment by o0Ignition0o** [comment]
I agree, LGTM :)

**Comment by Noxivs** [comment]
I agree ;)

**Comment by icefoxen** [comment]
I agree.

**Comment by emilio** [comment]
All fine for me.

**Comment by nical** [comment]
Thank you all a ton for answering so quickly!
I feel terribly silly as I just found out that pathfinder is actually not MPL2 licensed (it's MIT+Apache like lyon), and so I am a lot less certain about making the switch all of a sudden.

I still like the reasoning behind MPLv2 so while I'm going to stick to MIT+Apache for now, I'll add in the contributing guidelines a note about the possibility to re-license future contributions to MPL2 to keep the door open.

Thank y'all though <3 and also thanks again for the contributions, small and big, that you've made to this project so far!

**Comment by pizzaiter** [comment]
I agree. Sorry for being so late!

(For what it's worth, I prefer MIT+Apache.)
