### ISSUE TITLE
Port the gfx_advanced example to glium.

### ISSUE THREAD

**Issue by nical** [nical/lyon#252]
[Glium](https://docs.rs/glium/) is a very popular graphics API, so it would be useful to have both a gfx and a glium version of the gfx_advanced example.

**Comment by orhanbalci** [comment]
I would like to work on this example. Started with the basic example. [glium_basic](https://github.com/orhanbalci/lyon/tree/master/examples/glium_basic) Please have a look and comment on the code.

**Comment by nical** [comment]
Neat! If you want to submit this in a pull request I'll happily take it.

**Comment by orhanbalci** [comment]
I tried to port advanced example [glium_advanced](https://github.com/orhanbalci/lyon/tree/master/examples/glium_advanced) It is somewhat laggy I think. Number of instances of Rust logo is not same either. I could not manage to get instancing working with glium.

**Comment by nical** [comment]
Hm, I just had a look at how glium does instancing and it's pretty opinionated API. If I understand correctly you don't get to tell glium "Draw this geometry N times", and instead you say "Draw this geometry once per element in this magic PerInstance buffer". In our case the per-instance data is the buffer of `Primitive`s, except that we want to store the primitives for several draw calls in the same buffer so we can't pass the whole buffer as `PerInstance`, and instead need to pass [a slice](https://docs.rs/glium/0.19.0/glium/struct.VertexBuffer.html#method.slice-1) of it that corresponds to the range of parameter we want to pass for each draw call.
Then glium does some magic to pass the instance data as vertex attributes (whereas I stored it in a uniform buffer in the gfx example, but what glium does is probably better in this case).

So it looks like you are pretty close. From there I would turn prim_buffer into a VertexBuffer instead of a UniformBuffer, remove the per_instance buffer and in the instanced draw calls do something that would look like `prim_buffer.slice(range).per_instance().unwrap()` where range is the range of Primitive data to use in the draw call.
Then in the shader you need to declare and use vertex attributes (instead of indexing in a buffer with gl_InstanceID).

I will probably be a little busy for the next two weeks, but shortly after christmas I'll happily help you finish this if you are blocked (I realize that the explanation I just gave probably only makes sense if you are very familiar with opengl).

**Comment by orhanbalci** [comment]
I,m not very familiar with opengl but your explanations are clear. I'll give it another shot.
