### ISSUE TITLE
fill_ellipse exposes the euclid Length type which is not re-exported through lyon

### ISSUE THREAD

**Issue by icefoxen** [nical/lyon#265]
So it looks like the intention is to have all math-y types used in lyon exposed via the `lyon::math` module, which defines and re-exports helpful stuff.

`fill_ellipse()` and `stroke_ellipse()` take a `euclid::Length` as parameter, but this type is not exposed in `lyon::math`, so I have to import it from `euclid`, which is weird when nothing else in my project directly depends on `euclid`.

If you want I'll gladly make a PR adding the `Length` type to `lyon::math` and updating the types.

**Comment by nical** [comment]
I removed the `Radians` alias (`Length<Rad, T>`) in euclid in favor of a proper angle type that can have good things, but I haven't updated lyon to use that yet. I'll do that soon and make sure to expose the angle type.

**Comment by icefoxen** [comment]
No rush!

**Comment by nical** [comment]
This is addressed by #268.
