### ISSUE TITLE
Cli docs? 

### ISSUE THREAD

**Issue by o0Ignition0o** [nical/lyon#287]
There's a lot of things going on in the cli (and there soon will be more once @SilentByte lands #285, and if I'm able to land #267) so I'm wondering if we could: 
- Maybe add more infos to the readme.md regarding the various usable commands
- Maybe add nice docs about the different parameters ?
- Leave it so since the --help flag is verbose enough ? 

What do you think ?

**Comment by nical** [comment]
I am not eager to maintain a comprehensive doc in parallel to the in-code `--help` so as much as we can I would rather make the `--help` as complete as possible and give a broader idea of what the cli app can do in the readme (and invite people to use `--help` to see all options in detail.

**Comment by o0Ignition0o** [comment]
Ok I'll try to add relevant messages to the commands I add then :) I'm closing the issue
