### ISSUE TITLE
Custom formatting of the tessellated output in the CLI app.

### ISSUE THREAD

**Issue by nical** [nical/lyon#289]
It would be great to be able to specify a custom format for the vertices of the tessellator, in order to filter out unnecessary information and have custom formats:

something like:

```
cargo run -- tessellate -i mypath.txt --format "{ pos; [{{position.x}}, {{position.y}}], normal: [{{normal.x}}, {{normal.y}}] },"
```

Using some kind of syntax like `{{variable.member}}` to match the parameters (or something else), that could provide all of the information available in fill and stroke vertices.

A bit like `println!` but at runtime.

**Comment by zen3ger** [comment]
I have a yet not-too-sexy toy application that can replace `{var}` tags in user input with the value of `var`.
My question would be whether the `--format` flag should only define how each `vertex` printed here:
```rust
    try!{ write!(&mut *output, "vertices: [") };
    let mut is_first = true;
    for vertex in &buffers.vertices {
        if !is_first {
            try!{ write!(&mut *output, ", ") };
        }
/// >>>
        try!{ write!(&mut *output, "({}, {})", format_float(vertex.x, float_precision),
                                               format_float(vertex.y, float_precision)) };
/// <<<
        is_first = false;
    }
    try!{ writeln!(&mut *output, "]") }
```
or it should do a bit more than that...

**Comment by nical** [comment]
Great! being able to specify how each vertex is specified is definitely a good start. We can go from there and If you have ideas for a good syntax to specify how the whole output is formatted I'm all for it.

**Comment by zen3ger** [comment]
I was experimenting with something like
```
"vertices: [ \n@verticies{sep=\n}{ \t({position.x},{position.y})} \n]\n"

//prints:
vertices: [
    (1,2)
    (3,4)
]
```
The `@iterable{sep=itemseparator}{itemformatter}` is like a 'for-each' format marker. This formatting __may__ have some Latex vibe which I'm not sure how I feel about it. If you think it looks OKish, I'll start patching up format parser.

**Comment by nical** [comment]
Sounds good to me! So we'd escape `{` as `\{' for brackets that we do want to insert in the output as opposed to variables?

**Comment by zen3ger** [comment]
I'd go with that. The `{{` escaping  like in `println!()` seems too noisy.

**Comment by zen3ger** [comment]
Checkout #362 for the almost OK version. :smile:
