### ISSUE TITLE
Is it possible to convert VertexBuffers into a bitmap ?

### ISSUE THREAD

**Issue by Brooooooklyn** [nical/lyon#317]
Sorry, I'm new to graphics programing, and I need to generate bitmap directly. And I want to know if there is a way to generate bitmap like: `&[u8]` from `VertexBuffers`. Thank you !

**Comment by nical** [comment]
Hi! the usual way to use the vertex buffers is to write a bit of OpenGL/gfx-rs/glium/etc and render it on the GPU (see the examples in the repository). It is also technically possible to render the triangles directly on the CPU using the [toy triangle rasterizer](https://github.com/nical/lyon/blob/master/extra/src/triangle_rasterizer.rs#L42) but this piece of code is mostly meant to write automated tests so it's not particularly ergonomic or fast, and it doesn't do any anti-aliasing.

If you need something more polished/powerful to render triangles on the CPU, there are probably a few crates out there for software triangle rendering like https://github.com/novacrazy/rust-softrender
