### ISSUE TITLE
lyon_geom: How to make serde optional?

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#320]
Currently, `serde` isn't optional, afaiu. The [serialization](https://github.com/nical/lyon/blob/master/geom/Cargo.toml#L16) feature is mandatory, event through that `serde` marked as optional.

I'm not good with cargo features and I can't find a way to disable it.

**Comment by nical** [comment]
I am sort of discovering cargo features so I might have not done it properly, I'll sort this out before publishing the next version on crates.io. One thing to note is that the next version of euclid will have optional serde, but it's not published yet so, even if you disable serde in lyon, euclid ends up depending on it anyway, but that will be fixed very soon.

**Comment by RazrFalcon** [comment]
That exactly my problem. I managed to disable `serde` in `lyon`, but `euclid` still uses it.

**Comment by nical** [comment]
Alright then, euclid should be published next week and lyon updated right after that. I might rename the "serialization" feature into "serde" in the process. Serde will be completely optional in lyon's next release.

**Comment by RazrFalcon** [comment]
Thanks.

**Comment by nical** [comment]
Fixed in #322.
