### ISSUE TITLE
lyon_geom: CubicBezierSegment::bounding_rect returns invalid results

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#328]
I'm trying to use `CubicBezierSegment::bounding_rect` for path's bounding box detection, but I stumbled on a possible bug.

Looks like for some curve this method returns invalid results.

I made a test application to reproduce the error: [lyontest.zip](https://github.com/nical/lyon/files/1713533/lyontest.zip) (`cargo run -- test.svg`)

It will output this text:
```
226: Rect((0.32624817x5.453125) at (75.84563,239.29688))
C 75.94140625 239.5390625 76.03515625 239.7734375 76.171875 240
404: Rect((0.3262787x5.453125) at (122.8456,239.29688))
C 122.94140625 239.5390625 123.03515625 239.7734375 123.171875 240
10.9375 231.95313 162.56812 12.796875
10.9375 231.95313 162.23438 8.046875
```

`226` and `404` are suspected segments.  Below them is actual curves. And last two lines are calculated bboxes. As you can see the first one is bigger than the second one.

The `test.svg` contains two overlapping paths: first one (black) is original and the second one (blue) has been flattened by `cairo`.

Here is a visualization of bboxes (you can make one by yourself, see comments in the example):
![bboxes](https://user-images.githubusercontent.com/725494/36063927-1b19e930-0e8c-11e8-81bd-35797919502b.png)

PS: according to the visualization there are not only two broken segments, but only two of them impacts the bbox.

Affected versions: 0.9 and git master.

**Comment by nical** [comment]
Thanks again for filing bugs and also thanks for the test case, it was very helpful. The buggy function had a few tests but they didn't cover the case where the cubic term of the derivative is nil and there was a silly mistake there.

The test case looks a lot better with #331:

![rect2](https://user-images.githubusercontent.com/264854/36078764-375fbb52-0f7b-11e8-8bb7-f642432bfa40.png)

**Comment by RazrFalcon** [comment]
Thanks. Everything works fine now.
