### ISSUE TITLE
Implement bevel line joins.

### ISSUE THREAD

**Issue by nical** [nical/lyon#34]
The path stroke tessellator has a very naive implementation of line joins that does not support bevel joins.

The relevant par of the SVG specification is here: https://svgwg.org/specs/strokes/#LineJoin

This should be implemented in [tessellation/src/path_stroke.rs](https://github.com/nical/lyon/blob/master/tessellation/src/path_stroke.rs).

See the (work in progress) [stroke tessellation wiki page](https://github.com/nical/lyon/wiki/Stroke-tessellation) for information about how the tessellator works.

**Comment by o0Ignition0o** [comment]
Ok I want to give this one a shot when I have time, can you please assign me ? :)

**Comment by o0Ignition0o** [comment]
Hey @nical , I've just found a stackexchange post https://graphicdesign.stackexchange.com/questions/59018/what-is-a-bevel-join-of-two-lines-exactly-illustrator which claims : 

> The two points are orthogonal to their respective segments and half the thickness away from them

Can you please confirm the is the approach I'm supposed to take in order to tackle the issue ? 

https://i.stack.imgur.com/TWRGI.png 

Thanks a lot :)

**Comment by nical** [comment]
Hi @o0Ignition0o, yes, this looks right. The other join on this stackexchange post is a miter-clip join which we should also get to eventually, but first things first :)

**Comment by EloD10** [comment]
I just see that : "o0Ignition0o commented 9 days ago ", I thought I was reading 9 months, i'm so sorry if you were working on that issue @o0Ignition0o

**Comment by o0Ignition0o** [comment]
It's ok ! nice one btw, I was trying hard to find a way to cover the  class with unit tests, so it should be fine :)
