### ISSUE TITLE
Make the source code easier to unserstand and discover.

### ISSUE THREAD

**Issue by nical** [nical/lyon#36]
A followup issue from discussions in #32.

Relevant comment from @Drakulix:
> [...] I have a hard time to figure out what parts of it can be used in combination and how they should fit together.
> 
> [...] I don't feel like I would know where to start without studying the examples in great detail at first (which was even more difficult, before you added the new simpler example).
> 
>  This could most likely be resolved by some explanation and maybe some smaller examples in the giant meta-crate. That would be the place, I would expect a gentle introduction about how to start using this project.

Looks like we need at least:
 - [ ] A "getting started" section in the documentation of the meta-crate with examples.
 - [ ] More standalone examples preferably as simple and focused as possible.
 - [x] More detailed explanations about which crates are useful for what, which crates are optional and how the crates interact with one another.

**Comment by Drakulix** [comment]
This has improved so much with the last release. Thanks! :)

**Comment by nical** [comment]
You're welcome and thank you too! These improvements were made thanks to the feedback you gave. The docs are still far from perfect so don't hesitate to point me to any of its shortcomings.

**Comment by LU15W1R7H** [comment]
I think the codebase would also benefit from some restructuring. This would make the "discovering" easier.
Some things are not as organized, which makes reading the code harder.
