### ISSUE TITLE
lyon_tesselation: stroke_circle panics on debug when tolerance >= radius * 2

### ISSUE THREAD

**Issue by ThatsNoMoon** [nical/lyon#366]
Here's the error message I got.
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/basic_shapes.rs:615:22
```

I have a very basic understanding of why this happens, and possibly it *should* panic, but this behavior should at least be documented.

**Comment by nical** [comment]
Thanks for filing this. The goal is that it shouldn't panic even with unusual input parameters so this is definitely a bug, I'll look into it some time this week.
