### ISSUE TITLE
CubicBezierSegment.line_segment_intersections_t fails when the line segment is horizontal  or vertical

### ISSUE THREAD

**Issue by kleintom** [nical/lyon#423]
[example.txt](https://github.com/nical/lyon/files/2469620/main.txt)

If you run
```rust
curve.line_segment_intersections_t(&line)
```
where line is horizontal or vertical, you never get intersections.  Internally we compute the intersections of the curve with the line generated from the line segment, and then return those intersections that are contained in the bounding box of the segment.

Rect.contains says
```
/// Returns true if this rectangle contains the point. Points are considered
/// in the rectangle if they are on the left or top edge, but outside if they
/// are on the right or bottom edge.
```
but internally the result conditions get [&&ed](https://docs.rs/euclid/0.19.2/src/euclid/rect.rs.html#201-204). Since the bounding box of a horizontal or vertical line has one of its dimensions zero, it can't contain any point.

I think the solution here is to just rewrite the contains by hand in this case to do the right thing with 0-width/height rectangles.  I'll post a patch later.

**Comment by nical** [comment]
Nice catch! You are right.
