### ISSUE TITLE
Use GeometryBuilder instead of BezierGeometryBuilder in the FillTessellator.

### ISSUE THREAD

**Issue by nical** [nical/lyon#43]
`BezierGeometryBuilder` is a super-set of the `GeometryBuilder` trait that adds an extra `add_quadratic_bezier` method. This method is not used by the fill tessellator in [path_fill.rs](https://github.com/nical/lyon/blob/master/tessellation/src/path_fill.rs), so it should mostly be a minor refactoring to replace one trait with the other in the function.

**Comment by o0Ignition0o** [comment]
Hey there :) I've been lurking around easy first pull requests on Rust so I can start working on it a bit, and I've just landed on your issue on github. It really looks like a simple refactoring thing, but I would like to write a failing unit test first, and let it pass. I'd love to be assigned if anyone can provide me hints on how I'm supposed to do this :)

**Comment by nical** [comment]
Hey @o0Ignition0o, I am fighting with github which isn't letting me assign the bug to you (my github-justu isn't quite there yet). In the mean time here are some pointers about the task at hand: In this case this change is not an observable behavior so I can't think of a unit test you could write for it (although I salute the approach!). For this API change, go to the [path_fill.rs](https://github.com/nical/lyon/blob/master/tessellation/src/path_fill.rs) file on your clone of the repository and replace the usage of BezierGeometryBuilder by GeometryBuilder in that file. there might be a few other places to fix once the API change is made, so you'll want to go through the different sub-crates of the repository and run `cargo test` on them to check that there is no mismatch between the usage of the API and the change you've made. If you are on linux or mac, you can run `./all.sh test` at the root of the repository to automatically run cargo test on all folders.

Once you have done the change (or part of it and want to get some feedback), submit a pull request. If you are not familiar with the pull request workflow, let me know and I'll walk you through it.

Don't hesitate to ask any questions.

**Comment by o0Ignition0o** [comment]
Hey thank's a lot for your reply :) 

I've somehow submitted a PR, which only concerns the path_fill.rs so far. ( https://github.com/nical/lyon/pull/45 ) I'll check tonight if I can refactor some other files :) 

Oh and By the way you can find me on irc as ignition (although I can't reach IRC while at work) =)

**Comment by nical** [comment]
I haven't managed to assign you, and it appears that github won't let me assign issues to people who are not owners of the project, so let's work without assigning issues for now. Thanks for the PR, is is fixed now so I'll close this issue.
