### ISSUE TITLE
PathEvent::Arc to SvgEvent::ArcTo ?

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#434]
Looks like it's not supported: https://github.com/nical/lyon/blob/0ce27b5e01619a2b1a002014a2d77a25f9d257d8/path/src/path_state.rs#L43..L46

**Comment by nical** [comment]
Oops that's an oversight. What's missing here is that the previous control point which gives the tangent for smooth path operations is not set properly.

**Comment by nical** [comment]
Actually I had a look at the SVG spec and it says:

> If there is no previous command or if the previous command was not a Q, q, T or t, assume the control point is coincident with the current point.

Which corresponds is what this code already does.

**Comment by RazrFalcon** [comment]
Isn't arc should have a radius and an angle? Current code creates a line, afaiu.

**Comment by nical** [comment]
This code doesn't generate segments, it's just a helper that keeps track of some state that is needed to convert relative and smooth curve segments into absolute ones.

**Comment by RazrFalcon** [comment]
I see. But anyway, the question is the same: how to convert PathEvent::Arc to SvgEvent::ArcTo?

**Comment by RazrFalcon** [comment]
`lyon_path::PathEvent::Arc` has 4 values, but `lyon_geom::arc::Arc` requires 5.

Looks like `x_rotation` is missing.

**Comment by RazrFalcon** [comment]
Also, I've tried implementing `lyon_path::builder::PathBuilder`, but it doesn't provide `start_angle`.

**Comment by nical** [comment]
The missing parameter in `PathEvent::Arc` is `start_angle` because it can be deduced from the current position of the path and the center of the arc.
There's an example going from the event to the arc object here: https://github.com/nical/lyon/blob/0ce27b5e01619a2b1a002014a2d77a25f9d257d8/path/src/builder.rs#L389

Your question makes me realize that this code is poorly documented, I'll try to make it less ambiguous.

**Comment by RazrFalcon** [comment]
I thinks the actual code is 

https://github.com/nical/lyon/blob/0ce27b5e01619a2b1a002014a2d77a25f9d257d8/path/src/builder.rs#L317

So in my case it will be:

```rust

impl lyon_path::builder::PathBuilder for Builder {
    // ...

    fn arc(&mut self, center: Point, radii: Vector, sweep_angle: Angle, x_rotation: Angle) {
        let arc = lyon_geom::arc::Arc {
            start_angle: (self.current_position() - center).angle_from_x_axis() - x_rotation,
            center, radii, sweep_angle, x_rotation,
        };
        self.last_pos = arc.sample(1.0) - arc.sample_tangent(1.0);
        let arc = arc.to_svg_arc();

        self.path.push(svgdom::PathSegment::EllipticalArc {
            abs: true,
            rx: arc.radii.x as f64,
            ry: arc.radii.y as f64,
            x_axis_rotation: arc.x_rotation.to_degrees() as f64,
            large_arc: arc.flags.large_arc,
            sweep: arc.flags.sweep,
            x: arc.to.x as f64,
            y: arc.to.y as f64,
        });
    }
}
```

Sadly I can't test it now, but I'm hope it will work correctly.

**Comment by RazrFalcon** [comment]
Also, looks like this flag is unused:

https://github.com/nical/lyon/blob/0ce27b5e01619a2b1a002014a2d77a25f9d257d8/path/src/default.rs#L218

**Comment by nical** [comment]
> I thinks the actual code is

Oops, yes sorry.

I'm not sure about this line:

> self.last_ctrl = arc.sample(1.0) - arc.sample_tangent(1.0);

What you are doing here is remembering the equivalent of the previous control point such that the next smooth command will not have a sharp angle, however the SVG spec says that smooth curves only work if the previous command is of the same kind. See the wording in https://www.w3.org/TR/SVG/paths.html for smoot cubic béziers:

> The first control point is assumed to be the reflection of the second control point on the previous command relative to the current point. (If there is no previous command or if the previous command was not an C, c, S or s, assume the first control point is coincident with the current point.)

Surprisingly it means that a smooth cubic bézier doesn't "work" after a quadratic bézier even though we could have picked the quad's control point.

(BTW this means that lyon's handling of smooth curves is incorrect. I'll have to fix that).

**Comment by RazrFalcon** [comment]
>I'm not sure about this line

Yes. I've already removed it.

And yes, SVG paths are pretty complex.

**Comment by nical** [comment]
To make sure I made this test case showing a quadratic bézier followed by a smooth cubic and it indeed creates a sharp angle. 

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg8"
   version="1.1"
   viewBox="0 0 297 210"
   height="210mm"
   width="297mm">
  <defs
     id="defs2" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     transform="translate(0,0)"
     id="layer1">

<path
       id="path"
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       d="M 0 0 Q 100 0 100 100 S 200 100 200 0 Z"
/>

  </g>
</svg>

```

**Comment by nical** [comment]
I think that this can be closed now.
