### ISSUE TITLE
FillTesselator ignores winding order of input path

### ISSUE THREAD

**Issue by haxtibal** [nical/lyon#435]
The FillTessellator seems to always generate triangles in counter clock wise winding order, no matter if the input path was CW or CCW. Probably this is intentional (I see #217 and #220), just wanted to leave a note that in my use case the following behavior would be preferable:
- if input path is CW, each output triangle is CW
- if input path is CCW, each output triangle is CCW

Is there any way to achieve this with lyon 0.11.0 (besides swapping indexes after tessellation)? Or any interest in adding such an option for a future release?

FWIW, I'm using lyon to tessellate 3D polyhedron to generate OpenGL assets (project each face onto 2D plane, then tessellate, then map indexes back to 3D). Winding order matters, because of backface culling.

Below is some test code to demonstrate current lyon behavior
```
extern crate lyon_tessellation;

#[cfg(test)]
mod tests {

use lyon_tessellation::{FillError, FillOptions, FillTessellator, FillVertex};
use lyon_tessellation::path::builder::FlatPathBuilder;
use lyon_tessellation::path::default::{Path, PathSlice};
use lyon_tessellation::geometry_builder::{VertexBuffers, simple_builder};
use lyon_tessellation::geom::math::point;
use lyon_tessellation::geom::euclid::Point2D;

#[derive(Debug,PartialEq)]
enum WindingOrder { CW, CCW }

fn winding_order(a: Point2D<f32>, b: Point2D<f32>, c: Point2D<f32>) -> WindingOrder {
    // assumption: x increases left to right, y increases top to bottom
    if (b.to_vector() - a.to_vector()).cross(c.to_vector() - a.to_vector()) >= 0.0 {
        return WindingOrder::CW;
    }
    return WindingOrder::CCW;
}

fn tessellate_path(path: PathSlice) -> Result<VertexBuffers<FillVertex, u16>, FillError> {
    let mut buffers: VertexBuffers<FillVertex, u16> = VertexBuffers::new();
    let mut vertex_builder = simple_builder(&mut buffers);
    let mut tess = FillTessellator::new();
    tess.tessellate_path(
            path.path_iter(),
            &FillOptions::tolerance(0.05),
            &mut vertex_builder
        )?;
    return Ok(buffers);
}

#[test]
fn test_winding_order() {
    // merely test the test...
    assert_eq!(WindingOrder::CW, winding_order(Point2D::new(0.0, 0.0), Point2D::new(1.0, 1.0), Point2D::new(0.0, 1.0)));
    assert_eq!(WindingOrder::CCW, winding_order(Point2D::new(0.0, 0.0), Point2D::new(1.0, 1.0), Point2D::new(1.0, 0.0)));
}

#[test]
fn test_ccw() {
    let mut builder = Path::builder();
    builder.move_to(point(0.0, 0.0));
    builder.line_to(point(1.0, 1.0));
    builder.line_to(point(1.0, 0.0));
    builder.close();
    let triangles = tessellate_path(builder.build().as_slice()).unwrap();
    assert_eq!(WindingOrder::CCW, winding_order(
            triangles.vertices[triangles.indices[0] as usize].position,
            triangles.vertices[triangles.indices[1] as usize].position,
            triangles.vertices[triangles.indices[2] as usize].position
        ));
}

#[test]
fn test_cw() {
    let mut builder = Path::builder();
    builder.move_to(point(0.0, 0.0));
    builder.line_to(point(1.0, 1.0));
    builder.line_to(point(0.0, 1.0));
    builder.close();
    let triangles = tessellate_path(builder.build().as_slice()).unwrap();
    assert_eq!(WindingOrder::CW, winding_order(
            triangles.vertices[triangles.indices[0] as usize].position,
            triangles.vertices[triangles.indices[1] as usize].position,
            triangles.vertices[triangles.indices[2] as usize].position
        ));
    // ^------ This test fails, gives counter clock wise triangle even if input path was clock wise
}

}
```

**Comment by nical** [comment]
Hm, the tessellator's algorithm isn't set up to carry this information until the part where triangles are produced. I don't think it would be easy to add, and I'm not sure it can be implemented consistently with self-intersection.
How would this work, for example, with two intersecting circles, one of which being clock-wise and the other counter-clock-wise? The two filled areas would have a mix of CW and CCW edges.

**Comment by haxtibal** [comment]
> I don't think it would be easy to add

Not too bad. I can carry winding information outside the tessellator. If lyon guarantees to always generate CCW triangles, there's at least no need to calculate the winding order for each output triangle, and all I have to do is swapping two indexes if CW is needed. The performance impact should be negligible.

> two intersecting circles, one of which being clock-wise and the other counter-clock-wise

Yes, that'll be a problem. I didn't think of it, because in my use case there are no such intersecting paths. So thanks for your reply, just let's close this issue. I've got another request related API and indexes, will open a new issue for it.
