### ISSUE TITLE
Rust API guidelines.

### ISSUE THREAD

**Issue by nical** [nical/lyon#44]
Lyon should conform to the [rust API guidelines](https://github.com/brson/rust-api-guidelines).

[This blog post about elegant APIs in rust](https://deterministic.space/elegant-apis-in-rust.html) should be relevant as well.

**Comment by o0Ignition0o** [comment]
Just found a pretty cool talk from @killercup which might also be useful https://youtu.be/0zOg8_B71gE?list=PL85XCvVPmGQhvs1Rnet_24B-AI3YSM2YG
