### ISSUE TITLE
`attempt to subtract with overflow` when attempting to use large amounts of geometry

### ISSUE THREAD

**Issue by gabrielecirulli** [nical/lyon#440]
I've been playing around with Rust and I tried implementing Conway's Game of Life using [ggez](https://github.com/ggez/ggez).

I'm using ggez's mesh builder to render all of the cells in a single draw call. I've implemented a function to invert the grid (i.e. turn every dead cell into a live one), and it appears that when the game tries to render a huge amount of red squares, it causes an `attempt to subtract with overflow`. You can find my backtrace at the bottom.

I'm using:
- cargo 1.32.0 (8610973aa 2019-01-02)
- rustc 1.32.0 (9fda7c223 2019-01-16)

Here's a gist including my code (`main.rs` should be in `src/`) and my `Cargo.lock` file: https://gist.github.com/gabrielecirulli/7f11cbb6554b5ee910fb6e4b0decd110
You might have to follow these instructions to get SDL2 working: https://github.com/Rust-SDL2/rust-sdl2#user-content-requirements

Please note I've set up the window to fit my entire screen on a MacBook Pro, but it may not fit yours.

Backtrace:

```
$ RUST_BACKTRACE=1 ./target/debug/conways_game_of_life
Source <PhysicalFS root: /Users/work/Work/Rust/conways_game_of_life/./target/debug/resources>
Source <PhysicalFS root: /Users/work/Library/Application Support/conways_game_of_life>
Source <PhysicalFS root: /Users/work/Library/Application Support/conways_game_of_life>

min_neighbors_required_around_live_cell = 2
max_neighbors_required_around_live_cell = 7
neighbors_required_around_dead_cell = 5
thread 'main' panicked at 'attempt to subtract with overflow', /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/geometry_builder.rs:449:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:95
   8: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:59
   9: alloc::raw_vec::alloc_guard
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/geometry_builder.rs:449
  10: lyon_tessellation::path_fill::FillTessellator::add_vertex_with_normal
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:530
  11: lyon_tessellation::path_fill::FillTessellator::process_vertex
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:655
  12: lyon_tessellation::path_fill::FillTessellator::tessellator_loop
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:488
  13: lyon_tessellation::path_fill::PendingEdge::to_active_edge
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:352
  14: <std::collections::hash::map::RandomState as core::hash::BuildHasher>::build_hasher
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:327
  15: lyon_tessellation::FillOptions::default
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/basic_shapes.rs:820
  16: core::ptr::swap_nonoverlapping_bytes
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mesh.rs:205
  17: <conways_game_of_life::MainState as ggez::event::EventHandler>::draw
             at src/main.rs:276
  18: ggez::event::run
             at /Users/work/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/event.rs:282
  19: conways_game_of_life::main
             at src/main.rs:387
  20: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  21: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  22: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  23: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  24: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  25: conways_game_of_life::main
```

Unfortunately I don't have the experience to troubleshoot this issue further myself, but I thought it'd help you to get a heads-up about this if you're not aware of this. Let me know if I can provide further information.

**Comment by nical** [comment]
Hi @gabrielecirulli, thanks for filing this and providing the test case. I managed to reproduce the issue and what is happening is that lyon is generating a vertex and index buffer and there is some arithmetic with indices that is overflowing because the indices are stored as u16.
Lyon actually lets you chose what type to use for indices (the tessellator actually uses u32 internally). Ggez is using u16 for indices though apparently, see: https://github.com/ggez/ggez/blob/e7fca76362f5d3a3186ae91fec78e4cde40d0061/src/graphics/mesh.rs#L65

I'm almost 100% sure that this bug can be fixed on the ggez side by either using u32 for indices, or implementing a custom `GeometryBuilder` that generates an error when running out of indices if sticking to u16 is important.

On the lyon side I'll add some debug checks to make this error easier to understand.

**Comment by nical** [comment]
Sorry, actually ggez 0.4 appears to be using lyon version 0.10.x which was only allowing u16 for indices. So to fix this ggez also needs to update to a more recent version of lyon (generic index types were introduced in lyon 0.11).

**Comment by gabrielecirulli** [comment]
Thanks for your quick reaction! Looks like ggez 0.5 uses Lyon 0.11 so this issue will be redundant once it’s reeased. Closing!

**Comment by nical** [comment]
@gabrielecirulli happy to help! Note that lyon 0.11 introduced the choice of the index type, but [by the look of the code](https://github.com/ggez/ggez/blob/e7fca76362f5d3a3186ae91fec78e4cde40d0061/src/graphics/mesh.rs#L65) ggez is still using u16 for indices. So the issue won't be automatically resolved. They'd either need to switch to u32 or detect the overflow manually and handle the error. For example they could try to split and start building a separate mesh when the current one is close to  being full. I'm not sure what's best for them, as u16 indices is quite common for meshes and is enough for a lot of use cases.

I have to admit that lyon's API isn't making it nice nor obvious how to deal with running out of indices. I filed #443 to look into making this nicer.
