### ISSUE TITLE
PathEvent and elliptic arcs

### ISSUE THREAD

**Issue by nical** [nical/lyon#446]
Arcs bring a lot of complexity to path events for various reasons, one of which being that we can't determine the destination of the arc without knowing the initial point (the way `PathEvent::Arc` is represented). This is a bit annoying for some algorithms that end up needing to track information about the previous segments just to deal with arcs.

The reason `PathEvent` includes arcs is mostly because I was imitating cairo/skia for the path data structure, but lyon doesn't need to store arcs (anything interesting with curves happens either on a bézier or flattened approximation).

Two solutions:

 - (1) Remove `Arc` from the `PathEvent` enum. When building a `Path`, arcs would automatically be converted to a series of cubic bézier curves. This simplifies things for me a lot, but potentially removes a feature people might want.
 - (2) Keep `PathEvent::Arc`, but add a `to: Point` member to make some of the annoying cases easier to implement.

@RazrFalcon @pcwalton @icefoxen you are the main non-lyon consumers of the `lyon_path` crate as far as I know. Would removing the ability to store arcs in `Path` and `PathEvent` without bézier conversion happening under the hood be an issue for you?

If having a path that can represent arcs is important, I could add a separate `SvgPath` data structure that can store all svg events including arcs, relative and smooth events. It would provide an iterator but wouldn't have most of `Path`'s features (just a storage thing).

**Comment by RazrFalcon** [comment]
>without bézier conversion happening under the hood

So ArcTo segments will be simply skipped?

**Comment by nical** [comment]
> So ArcTo segments will be simply skipped?

They'll automatically get approximated with between 1 and 4 cubic bézier segments depending on the sweep angle and stored that way rather than storing an elliptic arc directly.

**Comment by RazrFalcon** [comment]
I'm fine with it.

**Comment by pcwalton** [comment]
Removing arcs would make my life easier. Go for it :)

**Comment by nical** [comment]
I made the change in #447.
