### ISSUE TITLE
Curve's normal at the specified offset

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#466]
How to get a path/curve normal/tangent at the specified offset/length?

**Comment by RazrFalcon** [comment]
I see. Thanks.

**Comment by RazrFalcon** [comment]
I've tried rendering derivatives for a simple curve and got a strange results:

`M 20 100 C 35 135 85 135 100 100 C 115 65 165 65 180 100`

![out](https://user-images.githubusercontent.com/725494/58274005-903f1680-7d9a-11e9-9413-7625f1e80bf8.png)

Rects positions calculated via are `sample()`. And lines are `derivative()`. 

Is this an expected behavior?

**Comment by nical** [comment]
Just to be sure: the lines are drawn from `pos` to `pos + d`, right?

**Comment by RazrFalcon** [comment]
Nope...

**Comment by RazrFalcon** [comment]
Thanks again!

![out](https://user-images.githubusercontent.com/725494/58282197-bb7f3100-7dad-11e9-8bc8-d1f592ca63d7.png)

**Comment by nical** [comment]
Cool, happy to help!
