### ISSUE TITLE
Inner and outer tessellation

### ISSUE THREAD

**Issue by kvark** [nical/lyon#470]
Is there an ability to constraint the tessellation threshold to strictly be positive or negative across the path? That could be useful for producing tessellations that are either completely within the path or fully contain it.

**Comment by nical** [comment]
I'm not 100% sure I understand the question. Are you referring to inflating the path without causing some regions to overlap? Are you looking at fills, strokes or both (the two tessellators are very different)?
The fill tessellator doesn't have curve offsetting features. There are a few papers on curve offsetting I can dig for you if that's what you are after. The stroke tessellator's offsetting is very naïve (it doesn't prevent self-overlap).

**Comment by anlumo** [comment]
I recently published a crate for polygon offsetting: https://crates.io/crates/offset-polygon

Note that it's far from perfect, there are a few corner cases where it fails.

**Comment by kvark** [comment]
@anlumo if I understand correctly, offsetting doesn't guarantee that the result is either fully inside or fully covering a given path.
That's one of the things that I'm asking for: a quick way to produce 2 tessellations of a a path: one that is fully within the path and another one that fully covers the path.

**Comment by anlumo** [comment]
Can you name an example of where it doesn't do that?

**Comment by kvark** [comment]
My understanding was that tessellation currently just tries to approximate the curve/path. If you can offset that polygon, what is the value for offset, such that the polygon starts to be fully inside or fully outside of the original path?

**Comment by anlumo** [comment]
Any negative offset value will make it to be fully inside. Any positive value will cause it to overlap the path on all places (it will still cover everything inside).

**Comment by nical** [comment]
I'm going to close this because intergating a feature like this one in the tessellator is complicated to implement and out of scope in the foreseeable future.
