### ISSUE TITLE
Uneven sampling of a linear cubic segment

### ISSUE THREAD

**Issue by RazrFalcon** [nical/lyon#472]
```rust
let curve = CubicBezierSegment {
    from:  F64Point::new(40.0,  100.0),
    ctrl1: F64Point::new(50.0,  100.0),
    ctrl2: F64Point::new(150.0, 100.0),
    to:    F64Point::new(160.0, 100.0),
};

assert!(curve.is_linear(1.0));

let mut x = 40.0;
for n in 0..11 {
    let offset = (n as f64) / 10.0;
    println!("{:.1} {:.1} {:.1}", offset, curve.sample(offset).x, x);
    x += 12.0;
}
```

Outputs:

```
0.0 40.0 40.0
0.1 45.5 52.0
0.2 55.4 64.0
0.3 68.4 76.0
0.4 83.7 88.0
0.5 100.0 100.0
0.6 116.3 112.0
0.7 131.6 124.0
0.8 144.6 136.0
0.9 154.5 148.0
1.0 160.0 160.0
```

Only the middle point and edges are matching up. Is this a bug or am I using it incorrectly?

**Comment by nical** [comment]
This is a property of cubic béziers. People take advantage of this for example to create easing curves for animations by using 1D béziers.

If you place first control point exactly at one third and the second control point exactly at two thirds between the start and end of the curve, the sampling pattern will be linear.

The same can actually be observed with quadratic béziers and bézier curves of all degrees: all of control points and endpoints of the curve must be evenly spaced for sampling along the curve to be linear.

**Comment by RazrFalcon** [comment]
Thanks. It works as expected now.
