### ISSUE TITLE
Please support euclid 0.20

### ISSUE THREAD

**Issue by andrewshadura** [nical/lyon#483]
I tried to build `lyon_geom` against `euclid` 0.20, and I’m getting a lot of errors due to API changes:
```
error[E0107]: wrong number of type arguments: expected 2, found 1
  --> src/quadratic_bezier.rs:23:15
   |
23 |     pub from: Point<S>,
   |               ^^^^^^^^ expected 2 type arguments
```

```
error[E0107]: wrong number of type arguments: expected 3, found 1
   --> src/quadratic_bezier.rs:248:41
    |
248 |     pub fn transform(&self, transform: &Transform2D<S>) -> Self {
    |                                         ^^^^^^^^^^^^^^ expected 3 type arguments
```
```
error[E0107]: wrong number of type arguments: expected 3, found 1
   --> src/lib.rs:253:27
    |
253 |     pub type Rotation2D = euclid::Rotation2D<f32>;
    |                           ^^^^^^^^^^^^^^^^^^^^^^^ expected 3 type arguments

error: aborting due to 167 previous errors
```
Could you please have a look and update to the new API?

Thanks!

**Comment by nical** [comment]
Sure thing. Euclid is likely to get a 0.21 soon-ish because there are some matrix convention changes planned so I originally planned to wait for that one but since you need it now I'll update to 0.19.

**Comment by nical** [comment]
https://crates.io/crates/lyon_geom

**Comment by andrewshadura** [comment]
Thanks! It would seem other crates (e.g. lyon_path) also need updating?

**Comment by nical** [comment]
Yes, a number of people only use lyon_geom so I was waiting for another motivating change to publish the rest of lyon updated to euclid 0.20 but if you or someone else needs them now I'll go ahead and publish them as well.

**Comment by andrewshadura** [comment]
I'm packaging a series of build dependencies of resvg for Debian; I'm fine
with just patching the dependency, so it's not a blocker for me 🙂

**Comment by nical** [comment]
Fair enough, I'll publish the other crates.
