### ISSUE TITLE
Why is lyon_geom::scalar private?

### ISSUE THREAD

**Issue by autumnontape** [nical/lyon#490]
I'm writing some generic trait implementations for lyon_geom types, and I have to write each one twice, once for `f32` and once for `f64`, because I can't write a trait bound for `lyon_geom::scalar::Scalar`. Is there a reason for this?

**Comment by nical** [comment]
That's an oversight, thanks for reporting.

Fixed in https://crates.io/crates/lyon_geom/0.14.1

**Comment by autumnontape** [comment]
Thanks for the quick response!
