### ISSUE TITLE
Incorrect tessellation of path w/ holes

### ISSUE THREAD

**Issue by Herschel** [nical/lyon#492]
Tessellation of this shape with holes produces unexpected results.

This was the minimal example I was able to produce.  Gist, modified from glium basic example:
https://gist.github.com/Herschel/a7088696f8c89d831f07ce820c715e28

Current output (lyon 0.14.1):
![image](https://user-images.githubusercontent.com/36278/66352901-9979eb80-e915-11e9-92f3-44999c089aeb.png)

Expected output-ish (Flash Player):
![image](https://user-images.githubusercontent.com/36278/66352953-b6162380-e915-11e9-968d-c4aaf6a3cd9b.png)

Seems like the tessellator adds a triangle jumping back to a previous subpath? I also tried adding variations of `PathEvent::Close` at the end of the subpaths, but no luck.

(cc https://github.com/ruffle-rs/ruffle/issues/77)

**Comment by nical** [comment]
Thanks for filing this and providing a reduced test case. I'll look into it shortly.

**Comment by nical** [comment]
It took me a lot longer than I hoped to find time to look into this, sorry. The fix is up in [version 0.14.2](https://crates.io/crates/lyon/0.14.2).
