### ISSUE TITLE
relative coordinate placement with window resizes

### ISSUE THREAD

**Issue by aentity** [nical/lyon#499]
Hi, so was adapting the wgpu example, and I was hoping for some guidance on how to make a svg always appear in top-right corner of screen, for example, even after window resizes.

As it is now, if you pan the svg up it always maintains relative distance (since it shrinks according to Y dimensions), but X pan won't, when the window is resized.

So I'm wondering if have any help or ideas how the wgpu example can be made to stay in a particular relative position, say top right corner.

**Comment by nical** [comment]
My suggestion would be to look for the distance between the origin and the edge of the screen which should only depend on the zoom factor and the window size.

You have:

```glsl
    vec2 world_pos = local_pos - u_scroll_offset + prim.translate + 5.0 * vec2(float(gl_InstanceIndex), 0.0);
    vec2 transformed_pos = world_pos * u_zoom / (vec2(0.5, 0.5) * u_resolution);
```

and you can go from there.

Discard the `+ 5.0 * vec2(float(gl_InstanceIndex)` part which I probably put there to debug something but isn't really meaningful.

Gives you more or less `transfomed = zoom * (local_position + primitive_origin + pan).

`pan = transformed / zoom - (local_position + primitive_origin)`

if you want a transfomed point of a certain local position (say the top-left corner) to be at a certain target position you need to apply a panning vector such that:

`pan = target_position / zoom - top_left_position.`

There are probably some constant factors to mingle with on top of that, but it's the general idea.
