### ISSUE TITLE
Implement UpToTwo::push

### ISSUE THREAD

**Issue by nical** [nical/lyon#52]
`UpToTwo<T>` is a simple stack allocated container that can contain zero, one or two elements. It is currently implemented in the bézier crate (see `up_to_two.rs`). It would be handy to have a method `push` (which would panic if the container already has two elements).

**Comment by emilio** [comment]
Note that that container sounds a lot like https://crates.io/crates/arrayvec.

In particular: `type UpToTwo<T> = ArrayVec<[T; 2]>;` may provide this kind of friendly API.

**Comment by o0Ignition0o** [comment]
Then we might want to refactor the bézier crate using this one, won't we ?

**Comment by emilio** [comment]
Whoops, I just submitted #55, happy to bikeshed about that, or how the API should look like, as you see fit.

**Comment by nical** [comment]
Fixed in #55.
