### ISSUE TITLE
Panic in lyon_tessellation::fill::FillTessellator::process_events

### ISSUE THREAD

**Issue by Shnatsel** [nical/lyon#521]
Feeding [this SVG file](https://en.wikipedia.org/wiki/File:Hawaiian_Eruption-numbers.svg) to wgpu_svg example results in a panic in `lyon_tessellation::fill::FillTessellator::process_events` with the following message:

> thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1

Tested on git commit 4651f1b20b508aeb3cd79e0d9252803e7325afa8 corresponding to version 0.15.2

**Comment by nical** [comment]
Thanks for filing. I can reproduce this locally, looks like the path builder has a bug causing one of the path to not be closed properly. I'll dig into this shortly.
