### ISSUE TITLE
SVGs are rendered upside down

### ISSUE THREAD

**Issue by Shnatsel** [nical/lyon#524]
The included test.svg renders the following way for me with the wgpu_svg example:

![Снимок экрана от 2019-12-28 21-09-27](https://user-images.githubusercontent.com/291257/71549012-cb4f9b00-29b6-11ea-92d0-efa069154d8b.png)

Reference render by Inkscape:

![test svg](https://user-images.githubusercontent.com/291257/71548999-b541da80-29b6-11ea-8b8d-df0f551199f2.png)

Tested on commit 5429662e95d776530c157680476dcfb107b9d74c

**Comment by Shnatsel** [comment]
This seems to affect all SVGs I've tried so far.

**Comment by nical** [comment]
Looks like it got mixed up when porting the examples from legacy gfx-rs with opengl to wgpu with vulkan.
