### ISSUE TITLE
tessellation::basic_shapes::{fill,stroke}_rectangle take different types of VertexConstructor.

### ISSUE THREAD

**Issue by flmng0** [nical/lyon#531]
When trying to use `fill_rectangle`, and `stroke_rectangle` with the same data type, implementing a `BasicVertexConstructor` is insufficient. 

`stroke_rectangle` takes a `StrokeVertexConstructor`, but `fill_rectangle` doesn't take a `FillVertexConstructor`, instead taking a `BasicVertexConstructor`.

Is there a particular reason for the inconsistency?

**Comment by nical** [comment]
Yes. The Fill and Stroke tessellator provide the constructor with a position and an "attributes" object that can tap directly into the tessellator's internal data structures to fetch some extra information like custom vertex attributes. When something in basic shapes interacts with `FillVertexConstructor` or `StrokeVertexConstructor` it means that it used to have it's own simple implementation at some point but was eventually replaced with something that uses the fill or stroke tessellator under the hood. It's a part of the API that needs an overhaul.

`fill_rectangle` still has one of these very simple and fast implementations that doesn't use the tessellatos internally and doesn't create these internal data structures so it can't interoperate with `FillVertexConstructor`.

It's likely that `fill_rectangle` and most of the functions in `basic_shapes` will disappear eventually and be replaced with a helpers to build paths for the simple shapes and  tessellate them via tessellators.

In the mean time if you prefer to avoid BasicVertexConstructor, I suggest working the fill and stroke tessellators directly.

**Comment by nical** [comment]
Fixed on the master branch (not published yet).
