### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#532]
On https://docs.rs/lyon_tessellation/0.7.4/lyon_tessellation/#the-output-geometry-builders
the example links
https://docs.rs/lyon_tessellation/0.7.4/lyon_tessellation/path_fill/index.html#examples and
https://docs.rs/lyon_tessellation/0.7.4/lyon_tessellation/path_stroke/index.html#examples go to 404 pages.

**Comment by nical** [comment]
From the look of the links, you are looking at a fairly old version of lyon's documentation. The examples in the repository have changed since then and the current documentation (version 0.15.5) should have more up to date links.

**Comment by HalfVoxel** [comment]
Hi

I see. Well then I'd like to request that the readme is updated to point to the latest documentation. Right now it points to https://docs.rs/lyon_tessellation/0.7.4/lyon_tessellation/#the-output-geometry-builders

**Comment by nical** [comment]
Oh, apologies. I totally misunderstood your initial report. I thought old doc was pointing to removed examples and didn't see that the readme had pinned some versions in the links. Sorry!
