### ISSUE TITLE
Confusing doc for FillOptions::handle_intersections

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#534]
lyon_tessellation::FillOptions::handle_intersections seems to have an inverted meaning.

The documentation states

> A fast path to avoid some expensive operations if the path is known to not have any self-intersections.
> Do not set this to true if the path may have intersecting edges else the tessellator may panic or produce incorrect results. In doubt, do not change the default value.
> Default value: false.

Which means that if you set it to true it does **not** handle intersections, which is the complete opposite of what one would expect from the name (or this is how I interpret it anyway, maybe other people interpret it differently).

I would suggest that the parameter is renamed to something like "ignore_intersections".
Changing the behaviour of it would probably be a bad idea as some users may be relying on the existing behaviour.

**Comment by nical** [comment]
Sorry, the documentation is mixed up, `handle_intersection: true` is the default while setting it to false disables the intersection handling code gaining speed at the expense of incorrectly tessellating or failing on some self-intersecting paths.
