### ISSUE TITLE
Builder::arc behaves weirdly if current position is not on the arc

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#536]
If you call Builder::arc when the current position of the builder is *not* exactly *radius* distance away from the center in the arc method call then the arc's first bezier curve will still start at the builders current position and it will just look weird.
This exposes implementation details since it is not obvious (or documented) how the path builder splits an arc into bezier curves.

I would suggest that the arc method should also do a line_to command to a point at exactly *radius* distance away from the center. I.e. it should do a line_to to the start of the arc.

**Comment by nical** [comment]
Thanks for pointing this out, your suggestion sounds good to me. I had a look at web specs and similar arc methods (for example on CanvasRenderingContext2D) have the behavior you suggest.

**Comment by HalfVoxel** [comment]
Yeah, I also looked at those. It seems like the most common behaviour.

One distinction of note is if it should perform a line_to or a move_to if the arc is the first thing in a path that is drawn.
If it does a line_to then you will always get a line from (0,0) to the start of the arc unless you manually do a move_to before that. However it can be really tricky to figure out where to do the move_to if you for example have a rotated ellipse shape.

I would suggest that:
* If the path has no existing points. Do a move_to the start of the arc.
* Otherwise, if the current position is already at the start of the arc, do nothing.
* Otherwise, do a line_to.

This makes it much easier to do simple things like just drawing a circle at a given point.

**Comment by nical** [comment]
Yes that makes sense.
