### ISSUE TITLE
The stroke tessellator does not propagate errors

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#545]
I cannot replicate this, but you might be interested in a panic that i found

```
thread 'main' panicked at 'assertion failed: b != c', tessellation/src/geometry_builder.rs:510:9
```

**Comment by nical** [comment]
I certainly am! Was it the stroke or fill tessellator?

**Comment by HalfVoxel** [comment]
Pretty sure it was the stroke tesselator.

**Comment by HalfVoxel** [comment]
It may be useful to know that there were only bezier curves imitating lines (i.e. the control points were identical to the corners) in the builder. There may however have been duplicate points in it.

**Comment by HalfVoxel** [comment]
Some more info. I think this might be happening when the index type overflows.
The reason is that the add_vertex! macro hides the actual overflow error and just returns a vertex with index 0. This will usually cause some other asserts to trip.

```rust
macro_rules! add_vertex {
    ($builder: expr, position: $position: expr) => {{
        let mut position = $position;

        if $builder.options.apply_line_width {
            position += $builder.attributes.normal * $builder.options.line_width / 2.0;
        }

        let res = $builder.output.add_stroke_vertex(
            position,
            StrokeAttributes(&mut $builder.attributes),
        );

        match res {
            Ok(v) => v,
            Err(e) => {
                $builder.builder_error(e);
                VertexId(0)
            }
        }
    }}
}
```

**Comment by nical** [comment]
Ouch! The initial intention was to propagate the error but that apparently never materialize. nice catch!
