### ISSUE TITLE
Incorrect curve flattening

### ISSUE THREAD

**Issue by HalfVoxel** [nical/lyon#547]
I found a case where the stroke tesselation is extremely incorrect.

What happens is that on a bezier curve it seems to only add a single vertex and then skip the remaining ones even though it is clearly not within tolerance.

```
let mut builder = Path::builder();
builder.move_to(point(9.8589325,53.186916));
builder.cubic_bezier_to(point(10.3262615,56.03796), point(8.514468,58.483364), point(7.0338364,60.40962));
builder.cubic_bezier_to(point(5.5532045,62.335873), point(6.1438327,61.547035), point(3.9364057,60.891937));
```

In the image below you can see the control points for a bezier curve and the incorrect tesselation.
It does not seem to depend on the tolerance given to the path tesselator. It is however extremely sensitive to the exact positions of the control points of the curve.

![Screenshot from 2020-03-10 12-11-06](https://user-images.githubusercontent.com/1144597/76308000-32000780-62ca-11ea-8e5a-6130c85bdaeb.png)

**Comment by nical** [comment]
This appears to be an issue with the flattening approximation (done either before or during tessellation).

**Comment by HalfVoxel** [comment]
Here is a video *after* #549 has been applied. You can see that the flattening is not very stable at all. It will fail very often.

https://arongranberg.com/temp/lyon_flattening_issue_547.mp4

**Comment by nical** [comment]
@HalfVoxel is the code of your editing tool avilable somewhere for me to find some test cases and investigate?

**Comment by HalfVoxel** [comment]
@nical 
You can use https://github.com/HalfVoxel/graphica

The vertices start out being linear, smooth them by selecting them (easiest to select all with `ctrl+a`) and pressing `ctrl+s`. Then you can move vertices around until you find an issue.
When you have found it, select a single vertex near the bug and press `ctrl+p`. This will print it out in a format that is easy to reproduce in code.

Here is a new test case for example:
```
builder.move_to(point(9.8589325,53.186916));
builder.cubic_bezier_to(point(10.3262615,56.03796), point(9.956957,56.587357), point(8.476325,58.51361));
builder.cubic_bezier_to(point(6.995693,60.439865), point(6.1438327,61.547035), point(3.9364057,60.891937));
Tolerance: 0.003229443
```

**Comment by nical** [comment]
Nice, thanks! I have a work-in-progress implementation of Raph Levien's cubic bézier flattening approach which basically works by first approximating the curve with a sequence of quadratic bézier segments and then flattening them. So far it generates more points than lyon's current flattening algorithm but it's less likely to run into weird issues with inflection points so I'm optimistic about it.

I'll play with it some more and check that performance doesn't regress too much, and hopefully land it this weekend or next week.

**Comment by nical** [comment]
I toyed around with the tool on the latest flattening changes and it looks like the issue is fixed.

**Comment by HalfVoxel** [comment]
Nice! All issues do indeed seem fixed!
Great job!
