### ISSUE TITLE
Regression since 0.15.6

### ISSUE THREAD

**Issue by dabreegster** [nical/lyon#558]
Since the 0.15.6 release in Feb, there's been some regression: 
![before](https://user-images.githubusercontent.com/1664407/77798307-d9ea3480-702f-11ea-9ede-3a2d7a837eb3.png)
became 
![after](https://user-images.githubusercontent.com/1664407/77798323-df477f00-702f-11ea-96a5-d30d2b72c667.png)

I'm using resvg + lyon to turn SVGs and text into polygons, via https://github.com/dabreegster/abstreet/blob/master/ezgui/src/svg.rs. The bug is even more pronounced when tuning FillOptions::tolerance. I fixed by pinning to 0235217bfa9826f29e8d5fc5dbdfa8a6e35ebdff. From context, maybe this is the same issue as #550? Maybe the changes since Feb warrant a new minor version, since this is a pretty big behavioral change?

Thanks for all of the work on lyon! Without it, I'd be stuck with the hassle of textures and larger image files.

**Comment by nical** [comment]
Ouch! This looks like a pretty bad flattening issues. The flattening code changed a lot recently. Which version of `lyon_geom` is reported in your Cargo.lock when the problem happens? If it isn't 0.15.1, could you update the dependency to 0.15.1 to see how it affects the issue.

**Comment by dabreegster** [comment]
The problem happens with 0.15.1. I'm trying to figure out how to force lyon_geom to 0.15.0, but [Cargo patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) seems to be for switching from crates.io to a git repo; there's not an easy way to keep using crates.io but force different patch versions. Working on it.

**Comment by dabreegster** [comment]
I tried individual commits. I think it broke at adf530bd6b9d67d719f88cfc41abc721742b8998; the last working one was 21fe9cb1c6d8e939050712a93e965b06aab6fb5e.

**Comment by nical** [comment]
The fix is up on crates.io in lyon_geom `0.15.2` (and I yanked `0.15.1` as the bug is bad enough). Turned out to be a silly edge case where a cubic bézier curve that could be exactly approximated with one quadratic curve would end up being approximated with no curve at all.

Thanks for the report!

**Comment by dabreegster** [comment]
Thanks for the quick fix! I confirmed it works.
