### ISSUE TITLE
Variable width strokes

### ISSUE THREAD

**Issue by nical** [nical/lyon#565]
Currently the line width is a constant parameter throughout the tessellation of the stroke. It would be nice to allow variations along the path.

Something like this could be done:

```rust
pub enum LineWidth {
    Constant(f32),
    /// The base line width and index of a custom endpoint attribute
    /// that the base linewidth will be multiplied to. 
    Variable(f32, usize),
}

pub struct StrokeOptions {
    // ...
    line_width: LineWidth,
    // ...
}
```

**Comment by LU15W1R7H** [comment]
I would suggest a more general way of describing the line width.
A closure might be the right choice, which returns the current line width given the position along the path, and probably some more arguments.

**Comment by nical** [comment]
The problem with a callback passed to the tessellator is that you would build the path and specify its per-endpoint line widths in separate places which is inconvenient in the common case.

What would the callback API allow that wouldn't be possible/practical by specifying variable line widths when building the path?
