### ISSUE TITLE
Should `path::transformed` take a `self` ?

### ISSUE THREAD

**Issue by M-Adoo** [nical/lyon#575]
When I use `path.transformed`, I noticed It always inner clone path, seems I have no way to avoid it.

```rust 
pub fn transformed<T: Transformation<f32>>(&self, transform: &T) -> Self {
    let mut result = self.clone();
    result.apply_transform(transform);

    result
}
```
Maybe it should take  `self` and let user choose whether to clone it ? like this:
```rust 
#[must_use]
pub fn transformed<T: Transformation<f32>>(self, transform: &T) -> Self {
    self.apply_transform(transform);
    self
}
```

**Comment by nical** [comment]
I'm not yet sure what the API for things like transforming, reversing paths, etc will look like. It's probable that in the end something more along the lines of `apply_transform` will be exposed. In any case I agree that reallocations should not be enforced if avoidable.

I'll try to have this figured out by the time the next breaking version of lyon is released (there's already quite a bit of API churn on master).

**Comment by nical** [comment]
I implemented your suggestion on master. It will take a little while before this is released, though, because there are a lot of API breaking changes in the work.
