### ISSUE TITLE
geom version doesn't match version on crates.io

### ISSUE THREAD

**Issue by atouchet** [nical/lyon#586]
https://github.com/nical/lyon/blob/master/geom/Cargo.toml

Here the version number is 0.15.2 but crates.io has 0.15.3 published. Is there an update missing here?

**Comment by Ameobea** [comment]
I'm also seeing an issue with `lyon_tessellation` where v0.15.8 is published to crates.io but it seems to be behind what's actually in the repo which says it's version 0.15.6.

**Comment by nical** [comment]
The master branch contains a lot of (breaking) changes that haven't been published yet. You can think of the master branch as an upcoming 0.16 branch, though I will update the version numbers in Cargo.toml at the time of publishing.
While the 0.16 work is ongoing I have also backported some fixes to the published 0.15 branch and that's where the newer 0.15.x versions you are seeing on crates.io are.
