### ISSUE TITLE
Webgpu example renders upsidedown on macos (inverted y)

### ISSUE THREAD

**Issue by felixfaire** [nical/lyon#589]
This may be an issue with webgpu currently but thought i would make you aware. It also starts stretched until a resize event occurs which corrects the aspect ratio.

Great work with the library! 

![image](https://user-images.githubusercontent.com/5576638/84491354-53430c00-ac9c-11ea-8a0a-c8b86e8c3976.png)

**Comment by nical** [comment]
Yeah I think the y-flip is a change of behavior in a recent webgpu version. I have been procrastinating fixing it but I will get to that eventually :)
Thanks for filing.
