### ISSUE TITLE
Overlaping polygons

### ISSUE THREAD

**Issue by mr1sunshine** [nical/lyon#591]
Hey! Thanks for the great library.
I have an issue when I have two polygons overlapped. For example for the following code:
```rust
pub fn build_polygons<Builder: SvgPathBuilder>(path: &mut Builder) {
    let polygon = [[0, 0], [400, 0], [400, 400], [0, 400]];

    let mut x_offset = 0;

    let points: Vec<Point> = polygon
        .iter()
        .cloned()
        .map(|dot| point((dot[0] + x_offset) as f32, dot[1] as f32))
        .collect();
    path.add_polygon(Polygon {
        points: &points,
        closed: true,
    });

    let mut x_offset = 380;

    let points: Vec<Point> = polygon
        .iter()
        .cloned()
        .map(|dot| point((dot[0] + x_offset) as f32, dot[1] as f32))
        .collect();
    path.add_polygon(Polygon {
        points: &points,
        closed: true,
    });
}
```

I get the following picture in the modified `wgpu` example:
![image](https://user-images.githubusercontent.com/31016524/85632255-a7c48f00-b67f-11ea-87c0-57c290513ffe.png)

Any ideas what could cause it? Is it expected?

**Comment by nical** [comment]
Hi, thanks for filing this and sorry for the delay. This turned out to be a bug in the tessellator where horizontal overlapping edges need a bit of special treatment. I'll publish a fix on the 0.15 branch (and crates.io) today.
