### ISSUE TITLE
Implement vertex anti-aliasing

### ISSUE THREAD

**Issue by nical** [nical/lyon#6]
The idea of vertex-aa is to extrude an 1px wide strip along the edge of a shape with a gradient. It should not be too hard to do for strokes, but trickier for fills especially in cases with self-intersections.

**Comment by nical** [comment]
Closing in favor of #185.

**Comment by Vengarioth** [comment]
Sorry to comment on a closed issue, would you still accept contributions for this?

**Comment by nical** [comment]
Absolutely!

**Comment by nical** [comment]
In case having a look at a project that implemented this can help you in any way, the source for skia's tessellator which has this feature is here: https://github.com/google/skia/blob/1c35e571c3f041069e2b16979a733d784c7f0f4c/src/gpu/GrTessellator.cpp

And this presentation touches on their vertex-aa implementation: https://docs.google.com/presentation/d/1DpM5QS6kCkIqQN034Zz6oFm201Gd2wvq6Z30QfWNhcA/
