### ISSUE TITLE
Tesselated polygon misses some triangles

### ISSUE THREAD

**Issue by jeroentervoorde** [nical/lyon#604]
Hi,

Thanks for the library! I am using this to triangle the following polygon but as you can see i am missing (2 apparently) polygons from the tesselated result:
![image](https://user-images.githubusercontent.com/3625507/92232909-a6011e00-eeaf-11ea-97ac-0b18319960c2.png)

The red part is part of the original geometry and the green part are the triangles.
I made a small repo using sdl2 (and sdl2-gfx) to visualize it:

https://github.com/jeroentervoorde/sdl2-polygon-render

Am i doing something wrong here? I already tried using the polygon method of the Builder instead but with the same result.

**Comment by nical** [comment]
Thanks for filing this and providing a testcase. I'll have a look some time this week.

**Comment by nical** [comment]
It took a little longer than I wanted but I finally looked into this and it turned out to be a tolerance thresholds that remained hard coded in the tessellator. Since you are working with very small geometry the tessellator ended up merging a point and an edge that it considered too close.

**Comment by nical** [comment]
Fix in published in [version 0.16.1](https://crates.io/crates/lyon_tessellation/0.16.1).
