### ISSUE TITLE
`fill_ellipse` missing since 0.15

### ISSUE THREAD

**Issue by khionu** [nical/lyon#606]
Possibly an oversight? Was porting some 0.13 code and found this discrepancy

**Comment by nical** [comment]
I'm removing the basic shapes tessellation routines in favor of creating paths out of them and using the normal tessellators. In lyon's next version there'll be an `add_ellipse` method for path builders. In the mean time you can build a path like this and use the fill tessellator:

```rust
        let dir = match winding {
            Winding::Positive => 1.0,
            Winding::Negative => -1.0,
        };

        use std::f32::consts::PI;
        let arc = Arc {
            center,
            radii,
            x_rotation,
            start_angle: Angle::radians(0.0),
            sweep_angle: Angle::radians(2.0 * PI) * dir,
        };

        path.move_to(arc.sample(0.0));
        arc.for_each_quadratic_bezier(&mut |curve| {
            path.quadratic_bezier_to(curve.ctrl, curve.to);
        });
        path.close();

```

**Comment by nical** [comment]
The difficulty here is that `FillVertex` has direct access to the tessellator's internal state to lazily compute some information, so it's very hard to provide the same API without using the tessellator itself. So I eventually decided to sacrifice some of the performance of basic shapes to remove maintenance burden and consolidate the API.

I'll keep that in mind and look for a way to reintroduce specialization without making the general case slower, but it's tricky.

In the mean time you could extract the latest version of the basic_shapes routines that are important to you before they were removed. Some of them like tessellating rectangles are pretty trivial.

**Comment by nical** [comment]
Actually I experimented a bit and it might not be as complicated as I feared.
