### ISSUE TITLE
Regression with some fill shapes in 0.17

### ISSUE THREAD

**Issue by adrian17** [nical/lyon#623]
We've noticed in https://github.com/ruffle-rs/ruffle that a shape with empty space inside started being incorrectly filled.

I have found this commit to cause the regression: https://github.com/nical/lyon/commit/75e1b0824ac62f61275d17899fb5a34a65039bfe

Before:
![2021-01-09_21-36-19](https://user-images.githubusercontent.com/4729533/104108340-f9eb9b80-52c3-11eb-8bca-ebd9b4f68d15.png)
After:
![2021-01-09_21-39-59](https://user-images.githubusercontent.com/4729533/104108341-fbb55f00-52c3-11eb-98f7-369c4d3960c9.png)

Colors are a bit unfortunate, but you can see that in "after" the right digit has the inside wrongly filled.
The left and right shape were made basically the same way and display the same in other tools; when dumped as SVG, they have simply slightly different paths, compare:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" height="60.2px" width="43.7px" xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(1.0, 0.0, 0.0, 1.0, 1.0, 1.0)">
    <path d="M41.7 46.55 L34.5 46.55 34.5 58.2 23.75 58.2 23.75 46.55 0.0 46.55 0.0 36.8 25.15 0.0 34.5 0.0 34.5 36.75 41.7 36.75 41.7 46.55 M23.75 36.75 L23.75 16.95 10.4 36.75 23.75 36.75" fill="#ff9900" fill-rule="evenodd" stroke="none"/>
    <path d="M41.7 46.55 L34.5 46.55 34.5 58.2 23.75 58.2 23.75 46.55 0.0 46.55 0.0 36.8 25.15 0.0 34.5 0.0 34.5 36.75 41.7 36.75 41.7 46.55 M23.75 36.75 L23.75 16.95 10.4 36.75 23.75 36.75" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.0"/>
  </g>
</svg>
```
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" height="59.5px" width="43.15px" xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(1.0, 0.0, 0.0, 1.0, 1.0, 1.0)">
    <path d="M41.15 46.0 L34.05 46.0 34.05 57.5 23.4 57.5 23.4 46.0 0.0 46.0 0.0 36.35 24.85 0.0 34.05 0.0 34.05 36.35 41.15 36.35 41.15 46.0 M23.4 16.75 L10.25 36.35 23.4 36.35 23.4 16.75" fill="#ff9900" fill-rule="evenodd" stroke="none"/>
    <path d="M41.15 46.0 L34.05 46.0 34.05 57.5 23.4 57.5 23.4 46.0 0.0 46.0 0.0 36.35 24.85 0.0 34.05 0.0 34.05 36.35 41.15 36.35 41.15 46.0 M23.4 16.75 L10.25 36.35 23.4 36.35 23.4 16.75" fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.0"/>
  </g>
</svg>
```

Let me know if you want this info in another form, like specific arguments to lyon.

**Comment by nical** [comment]
Thanks for reporting this and for providing simple test cases. I'll have a look soon.

**Comment by nical** [comment]
Thanks again for the report, the simple test case and the regression window. I published a fix in [lyon_tessellation 0.17.3](https://crates.io/crates/lyon_tessellation/0.17.3).

**Comment by adrian17** [comment]
Cool, thanks! How often do you update the main crate https://crates.io/crates/lyon ?

**Comment by nical** [comment]
I usually do but was in a bit of a hurry yesterday and assumed that regenerating the lockfile would be enough to pick up the fix. I'll update it today.
