### ISSUE TITLE
Implement computing the bounding rect for LineSegment and Triangle.

### ISSUE THREAD

**Issue by nical** [nical/lyon#65]
[LineSegment::bounding_rect](https://github.com/nical/lyon/blob/461447458ad9c8302c5ec573bcbe345953323bd4/bezier/src/line.rs#L59) and [Triangle::bounding_rect](https://github.com/nical/lyon/blob/461447458ad9c8302c5ec573bcbe345953323bd4/bezier/src/triangle.rs#L31) are currently unimplemented.

`bounding_rect` should retrun the smallest `Rect` that contains the object.

**Comment by jaemk** [comment]
Hey, I'd like to give this a try!

**Comment by nical** [comment]
@jaemk Excellent! Let me know if there is anything I can do to help you get started.

**Comment by nical** [comment]
Fixed in #67.
