### ISSUE TITLE
request for a minimal example of drawing lyon to a window

### ISSUE THREAD

**Issue by jiyinyiyong** [nical/lyon#654]
I'm not very sure but can we draw shapes with lyon directly to a window? the code `cli/show.rs` looks doing the trick but a lot of code is involved, any simple example to use lyon this way?

**Comment by nical** [comment]
There isn't. Lyon is meant to be integrated into rendering engines that use GPU APIs like OpenGL or WebGPU, but it only turns vector graphics into triangle meshes and it's up to the user to draw these meshes. It's not hard but it is indeed quite verbose to set up.

**Comment by jiyinyiyong** [comment]
I came to this issue since ggez(which I currently use) is no longer maintained, are there any other libraries you would suggest using?

**Comment by nical** [comment]
If you want to draw shapes on using the GPU you can look into pathfinder (also unmaintained but quite capable), ochre and piet. They all  require some non-trivial amount of code on your end but that's unavoidable if you want something that can be intergated with other GPU rendering logic. Nannou (a creative coding framework) uses lyon.

**Comment by jiyinyiyong** [comment]
Nannou is at a higher level than I expected. I was also thinking about using pathfinder in future but... seems I have to stay with ggez before I get ready to migrate away from lyon. thanks for the advice.

**Comment by nical** [comment]
Looks like your questions are answered. Good luck!
