### ISSUE TITLE
lyon_geom: Arc with negative sweep does not flatten properly

### ISSUE THREAD

**Issue by sameer** [nical/lyon#661]
Arc does not seem to flatten properly when the sweep is negative. I am not that familiar with the code for `lyon_geom` so first posting about this issue to check whether there's something wrong on my end or if there is actually a bug here.

In [flattening_step](https://github.com/nical/lyon/blob/master/crates/geom/src/arc.rs#L339), the sweep angle is used directly, and when negative, returns a negative step (seems all steps should be in the range [0.0, 1.0]?).

For full context, see sameer/svg2gcode#10. It returns 3 points instead of a smooth path. When I instead look at the cubic bezier segments and flatten those, it produced the expected result.

If this is a bug, I can submit a PR to change flattening to use quadratic/cubic bezier under the hood. Or if you are familiar with the implementation I could use some guidance on how to change the current logic to handle negative sweep properly.

**Comment by nical** [comment]
Thanks for filing this. I'll look into it soon.

**Comment by nical** [comment]
Thanks again. The fix is in lyon_geon 0.17.2.

**Comment by sameer** [comment]
Awesome, thanks so much! I'll give it a try
