### ISSUE TITLE
LineJoin missed when closing a path

### ISSUE THREAD

**Issue by simensgreen** [nical/lyon#670]
Red - maybe wrong
Green - correct

### Stroke:
![stroke](https://user-images.githubusercontent.com/34134129/122816445-68a33b00-d2df-11eb-9f37-abc1107e1837.png)

### Code
```rust
    let points = vec!
    [
        [0.08, 0.25],
        [-0.08, 0.0],
        [0.08, 0.0],
        [-0.08, -0.25],
    ];
    let mut path_builder = Path::builder();
    path_builder.begin(Point::from(points.first().unwrap().clone()));
    for i in 1..points.len()
    {
        path_builder.line_to(Point::from(points[i].clone()));
    }
    path_builder.end(true);
    let path = path_builder.build();
    let mut options = StrokeOptions::default();
    options.line_width = 0.01;
    options.tolerance = 1e-4;
    options.line_join = LineJoin::Miter;
    let mut buffer: VertexBuffers<[f32; 3], u16> = VertexBuffers::new();
    let mut tessellator = StrokeTessellator::new();
    tessellator.tessellate_path
    (
        &path,
        &options,
        &mut BuffersBuilder::new
            (
                &mut buffer,
                |vertex: StrokeVertex| { [vertex.position().x, vertex.position().y, 0.0_f32] }
            )
    ).unwrap();
    buffer.indices.reverse();
```
The code is taken out of context and may cause any errors, but this is all interaction with lyon and my code

**Comment by nical** [comment]
Thanks for filing this, I'll have a look soon.

**Comment by nical** [comment]
Oh wait no I see what's going on here. This is the correct behavior. There is a miter limit that you can configure in the stroke options that specifies how far the miter join can extend away from the stroke (if the two edges on each side of the join get close to parallel, the miter join could extend towards infinity if it wasn't limited). When a miter join goes past the miter limit it is turned into a miter-clip join.

See https://svgwg.org/svg2-draft/painting.html#StrokeMiterlimitProperty

**Comment by simensgreen** [comment]
Thanks for the clarification and sorry to bother you.
