### ISSUE TITLE
stroke in or outside of path

### ISSUE THREAD

**Issue by caperaven** [nical/lyon#691]
When I define a path (for a polygon) and I want to create a stroke on the inside or outside not (half in half out) is there a setting I can make to determine the position of the stroke.

**Comment by nical** [comment]
There isn't a setting for that, but if you happen to know which side is in and which side is out, you can get the [side](https://docs.rs/lyon_tessellation/0.17.8/lyon_tessellation/struct.StrokeVertex.html#method.side) from the `StrokeVertex` as well as the normal and offset the geometry either along or in the opposite direction of the normal depending on the side, to create that effect.

**Comment by caperaven** [comment]
Thanks for the feedback m8

**Comment by nical** [comment]
Closing since I think the question has been answered.
