### ISSUE TITLE
stroke rounded

### ISSUE THREAD

**Issue by caperaven** [nical/lyon#692]
Currently it seems that only the outside is rounded or beveled.
Is it possible to have the inside and outside rounded and beveled?

![image](https://user-images.githubusercontent.com/9447181/130086911-55b631ff-58b4-4858-8efe-129c8f7162c6.png)

**Comment by nical** [comment]
It isn't currently possible. There isn't something like that in SVG or similar standards that I know of, how would you define the radius of the extra interior rounding?

**Comment by caperaven** [comment]
To be honest, I am not sure, I would imagine that it would be related to scale based on the line width.
You will need to use the angle of the curve along with the line width.
Having said that, my math is not exactly the most brilliant so I am just guess here.

**Comment by nical** [comment]
I don't plan to extend the the join types beyond what's in the SVG/canvas spec for now.
