### ISSUE TITLE
Finding the length of a path

### ISSUE THREAD

**Issue by caperaven** [nical/lyon#695]
Is there a way for me to get the path length without having to walk it and calculate it from the distance?

**Comment by nical** [comment]
The fastest way to compute the total length of a path is to iterate over it and sum the length of each segment using the `length` or `approximate_length` methods of `LineSegment`, `QuadraticBezierSegment` and `CubicBezierSegment`.

**Comment by caperaven** [comment]
Would it make sense to bubble that up a bit height to the Builder as a feature?

**Comment by nical** [comment]
Added `lyon_algorithms::length::approximate_length`.
