### ISSUE TITLE
wgpu examples out of date

### ISSUE THREAD

**Issue by simbleau** [nical/lyon#708]
The wgpu version is > 0.10 now.

Current examples use 0.9.

**Comment by nical** [comment]
Yeah, thanks for the heads up. Keeping the examples up to date with wgpu isn't op priority and I'm told 0.11 is coming soon so I'll wait and got straight to wgpu 0.11 whenever it's there and I have time to spare (unless you or someone else want to do the update).

**Comment by simbleau** [comment]
I’ll consider submitting a PR since I’ve already updated it on my side with some tweaks.

I don’t feel comfortable submitting the PR yet because I used Naga to convert your shaders rather than rewrite it in WGSL… and the automatic conversion is ugly looking.

**Comment by simbleau** [comment]
So unfortunately I don't have the time to fix it all, because apparently cli also uses wgpu, which I was not expecting.

However on my fork - https://github.com/simbleau/lyon - I have updated the examples/wgpu_svg to use wgpu 0.10.0.
It is a bit different. For instance, there is no "swap chain" anymore. Those are called surfaces and things are accessed differently as well. 

Using my code should help you update the examples/wgpu easily and after, make the changes to cli.

**Comment by nical** [comment]
Thanks!

**Comment by simbleau** [comment]
I finally ended up converting and cleaning the shaders up to look almost identical to the originals, but in WGSL. (No need for `features = "SpirV"`!)

You may find them here, and trust me, it will save you a lot of time. Good luck.
https://github.com/simbleau/vgpu-bench/tree/main/crates/tess-lib/src/renderer/shaders

**Comment by nical** [comment]
Thanks again. I'll look into it and convert the examples in the lyon repo soon-ish then.

**Comment by nical** [comment]
wgpu updated to 0.11
