### ISSUE TITLE
How to subtract a polygon from another polygon

### ISSUE THREAD

**Issue by agmcleod** [nical/lyon#718]
Hi there, for a game project im working on, im looking at building navigation mesh by laying out a polygon, then removing shapes from it as a user adds things like temporary walls to the game.

My test example is setting up a 10,10 rectangle, with trying to subtract a 2,4 rectangle that's rotated at 45 degrees. 

Can see the purple rectangle in the middle, subtracting from the 10,10 rect. Leaving the filled blue section.

![image](https://user-images.githubusercontent.com/113275/136276771-8d853821-643c-4682-b6cc-f829eb85f1bb.png)

Here's what ive tried so far, thinking i could add a separate path, but it tessellates triangles that overlap the middle polygon im trying to subtract.

```rust
use lyon_tessellation::math::{point, Point};
use lyon_tessellation::path::Path;
use lyon_tessellation::{
    geometry_builder::simple_builder, FillOptions, FillTessellator, VertexBuffers,
};

#[derive(Copy, Clone, Debug)]
pub struct MyVertex {
    position: [f32; 2],
    color: [f32; 4],
}

fn main() {
    let mut output: VertexBuffers<Point, u16> = VertexBuffers::new();
    let mut geometry_builder = simple_builder(&mut output);
    let mut tessellator = FillTessellator::new();

    let mut path_builder = Path::builder();
    path_builder.begin(point(0.0, 0.0));
    path_builder.line_to(point(10.0, 0.0));
    path_builder.line_to(point(10.0, 10.0));
    path_builder.line_to(point(0.0, 10.0));
    path_builder.end(false);

    path_builder.begin(point(2.0, 4.0));
    path_builder.line_to(point(4.0, 2.0));
    path_builder.line_to(point(6.0, 8.0));
    path_builder.line_to(point(8.0, 6.0));
    path_builder.close();

    let path = path_builder.build();

    let result = tessellator.tessellate_path(&path, &FillOptions::default(), &mut geometry_builder);
    assert!(result.is_ok());

    println!("Vertices\n{:?}\n", output.vertices);
    println!("Indexes\n{:?}\n", output.indices);
}
```

**Comment by nical** [comment]
Hi, You are on the right path, the only issue as far as I can tell is that the second sub-path is not a rectangle, it's some sort of hourglass shape. Try chaging it to:

```rust
    path_builder.begin(point(2.0, 4.0));
    path_builder.line_to(point(4.0, 2.0));
    path_builder.line_to(point(8.0, 6.0)); // swapped the last two
    path_builder.line_to(point(6.0, 8.0)); //
```

**Comment by agmcleod** [comment]
Ah of course! lol. Thanks for catching my mistake there. Cheers!
