### ISSUE TITLE
lyon_geom requires euclid 0.22.4 or higher to build

### ISSUE THREAD

**Issue by PSteinhaus** [nical/lyon#737]
Hi!

We just received [a report](https://github.com/ggez/ggez/issues/993) where a user wasn't able to build lyon_geom, as his Cargo.lock file specified euclid version 0.22.3, which is enough to satisfy the requirement of euclid 0.22 that lyon_geom currently asks for. At the same time it's actually not enough to really build lyon_geom, as it uses [functionality only introduced in euclid 0.22.4](https://docs.rs/euclid/0.22.4/euclid/struct.Box2D.html#method.x_range).

Creating a new lock file of course solves this on the user side, so it's nothing too horrible.
Yet it's still unpleasent to run into such a build error, so I guess updating lyon_geom's Cargo.toml file to reflect the necessity of euclid >= 0.22.4 might be helpful :)

**Comment by nical** [comment]
Thanks for reporting this, I'll put out a new version of lyon_geom eith updated deps.

**Comment by nical** [comment]
Fixed in `lyon_geom 0.17.6`.
