### ISSUE TITLE
`move_to` command results in an extra stroke being rendered

### ISSUE THREAD

**Issue by murtyjones** [nical/lyon#749]
([You can replicate this behavior by running this repo](https://github.com/murtyjones/lyon-stroke-question))

While playing around with `lyon`, I noticed a couple of behaviors around stroke tesselation that seem uninutitive and I'm not sure whether I'm using it incorrectly or if there's some kind of bug.

### 1. Multiple lines being rendered

This series of drawing commands:

```rust
let mut builder = Path::builder().with_svg();
builder.move_to(point(0.0, 0.0));
builder.move_to(point(0.0, 20.0));
builder.line_to(point(0.0, 21.0));
builder.close();
let path = builder.build();
```

Seems like it should only result in one line being drawn. However, in this example linked above I'm seeing multiple lines being rendered using the stroke tessellator + wgpu:

![image](https://user-images.githubusercontent.com/708562/149016441-2aa0387c-3107-40d3-adb9-6b369dee66a2.png)

### 2.  `line_width` not respected

Specifying `line_width` on `StrokeOptions` like so:

```rust
    let options = StrokeOptions::tolerance(tolerance)
        .with_line_cap(LineCap::Round)
        .with_line_width(10.0);
```

...doesn't seem to make any change to the line that's rendered versus the default setting. In fact, the only way I've been able to change the thickness of the line is by modifying the "stroke primitive":

```
// Stroke primitive
cpu_primitives[stroke_prim_id] = Primitive {
    color: [0.0, 0.0, 0.0, 1.0],
    z_index: num_instances as i32 + 2,
    width: 5.0,
    ..Primitive::DEFAULT
};
```

**Comment by nical** [comment]
Hi, thanks for bringing this up.

This behavior was actually intentional (with code to handle it specifically), but I think I misinterpreted the SVG path specification: I thought that dots had to be inserted for moveto sequences but apparently they should be inserted when moveto is either followed by an empty segment (for example "M 1 1 L 1 1") or when the sub-path is closed directly (like "M 1 1 Z").

I'll change this behavior in the next version of lyon.

**Comment by murtyjones** [comment]
Got it, thanks.

> This behavior was actually intentional (with code to handle it specifically)

Could you point me to this part of the codebase? Purely for my own education.

**Comment by nical** [comment]
On the 0.17 branch (what's on crates.io) https://github.com/nical/lyon/blob/78185f2069a9863dd6af42aab6feb9eb58ad92e9/crates/tessellation/src/stroke.rs#L688
On master (stroke tessellator rewritten but not published yet): https://github.com/nical/lyon/blob/master/crates/tessellation/src/stroke.rs#L1209
