### ISSUE TITLE
Standardized codebase formatting

### ISSUE THREAD

**Issue by murtyjones** [nical/lyon#752]
I have a fork of `lyon` which I'm striving to keep up to date with this repo as much as possible. One issue I'm noticing is that a run of `cargo fmt` reformats quite a bit of the codebase, which could cause merge issues if done only downstream. So I'm wondering if it's OK for me to introduce some formatting enforcement in this repo that I can use in my fork as well.

maybe a pre-commit hook like this one: https://gist.github.com/hryniuk/e3f4ae34e37947d0ff55a3f63add90f8

(I'm happy to implement, just want to confirm before I do it)

**Comment by nical** [comment]
I don't want to enforce formatting in the CI, but running cargo format every now and then (using the stable rust channel and default formatting parameters) is fine (ideally in their own PRs).

**Comment by nical** [comment]
By the way if/when you make significant additions to your fork and you are comfortable with sharing them, I'm curious about what those might be. Let me know!

**Comment by murtyjones** [comment]
For sure! So far my changes are just scratching the surface; as I implement more interesting things that might generalize, I'll open issues to share them. 😄
