### ISSUE TITLE
Should `PathWalker` be replaced?

### ISSUE THREAD

**Issue by Mivik** [nical/lyon#787]
I'm creating an animation of a sprite moving along a path, and that's when I found PathWalker impractical. If the moving process is linear then we can still use it, but in fact the moving process is non-linear (see examples from [https://easings.net/](https://easings.net/)) and thus simply tweaking `interval` won't yield useful results.

I wonder if we can adopt `PathMeasure`, the approach in Skia. And if not, why is that? Is the use of `PathWalker` required by some design principles or something else?

New to these things and sorry for my probably incorrect English.

**Comment by nical** [comment]
Hi, are you working on top of the current crates.io release or the master branch? The path walker should let you move linearly (as in, at constant speed) along the path. However it is based on an approximation which you can tweak via a tolerance parameter. The lower the tolerance parameter, the better the approximation, at a performance cost. 

Try lowering the tolerance parameter (to some smaller value superior to 0.0) and let me know if it helps.

I just had a look at skia's `PathMeasure` code and it is very similar to the approach in lyon_algorithms. The most notable difference being whether or not to cache information for future use, and the fact that skia uses a fixed tolerance threshold which I suppose is intended to give acceptable precision when 1 unit of length corresponds to roughly one pixel.

**Comment by Mivik** [comment]
I'm working on top of the current crates.io release. And I think you've probably misunderstood my issue.

So basically, I understand how `tolerance` works. It works as a threshold, lowering which would produce results with higher precision as the path is tessellated into more segments.

My problem is, it's hard to obtain information about **specific points** on a path using `PathWalker`. For example, if I want to know the "mid-point" of a path, I'll have to write:

```rust
let length = approximate_length(&path, 0.01);
let counter = 0;
let mut pattern = RegularPattern {
    interval: length * 0.5,
    callback: |pos, _, _| {
        counter += 1;
        if counter == 2 {
            println!("The mid-point is {:?}", pos);
        }
        true
    },
};
walk_along_path(path.iter(), 0.0, pattern);
```

And what I expect is something like:

```rust
let length = approximate_length(&path, 0.01);
let measure = path.measure();
println!("The mid-point is {:?}", measure.position_at(0.5));
```

This is crucial when implementing path animation. Imagine an animation of a point moving along a path. If `PathMeasure` is introduced, I can simply go like:

```rust
fn on_update(&self, progress: f64 /*from 0 to 1, not guaranteed to change linearly*/) {
    draw_point(self.path_measure.position_at(progress * self.path_length));
}
```

While using `PathWalker`, I have to write codes like the first snippet I mentioned, and the time complexity will grow significantly.

**Comment by Mivik** [comment]
I have just known why did you misunderstand me. I said

> If the moving process is linear then we can still use it, but in fact the moving process is non-linear (see examples from https://easings.net/) and thus simply tweaking interval won't yield useful results.

But actually I wanted to say

> If the moving process is linear (for example, a linear animation) we can still use`PathWalker`, but in fact **I want the moving process to be non-linear** (I want to make a non-linear animation) (see examples from https://easings.net/) and thus simply tweaking interval won't yield useful results.

Sorry for my bad English again 😂

**Comment by nical** [comment]
Oh, I see!  no worries.

So the main reason the path walker uses real distances instead of normalized (between 0 and 1)  distances  is that it doesn't know about the entire length of the path until the very end, so to achieve what you want it would have to do exactly what you wrote in that mid-point example and it would double the cost (since measuring is the most expensive part).

Something with an API like skia's PathMeasure is possible but that needs a separate implementation so I'm probably not going to add it in the very short term.

In the mean time you can wrap the boilerplate in a helper function, something like:

```rust
pub fn find_position_at(path: PathSlice, t: f32) -> Point {
    let length = approximate_length(&path, 0.01);
    let mut position = None;
    walk_along_path(path.iter(), length * t, &mut |pos, _, _| {
        position = Some(pos);
        None
    });

    position.unwrap()
}
```

It's not a one-liner but not too bad either. That said I suspect that it might run into precision issues at t=1.0 because if the approximation in measure_path and walk_along_path have even a tity difference it might overshoot and not invoke the callback.

I'll think about it some more.

**Comment by Mivik** [comment]
Thank you for your solution!

So in `find_position_at`, we create a `PathWalker` and walk along the path to obtain the information. That's an feasible approach for sure, but IMO this will give rise to performance overhead, which can be significant under dense invocation such as animation rendering.

Though you said you're not considering to implement it in a short term, this functionality is pretty important in my project so I'm going to implement it anyway. Would you mind me starting a pull request after I finish?

**Comment by nical** [comment]
If you are going to do this repeatedly you'll for sure want to cache and reuse the path length at least.
You should try it out and see how far that gets you in terms of performace.

For something new to be included in lyon it will have to support custom path attributes which might be more work than what you'll want to put in (See for example the implementation of the path walker in the master branch). but I'd totally be interested.
