### ISSUE TITLE
ParseError while parsing SVG path in lyon 1.0

### ISSUE THREAD

**Issue by ogoffart** [nical/lyon#797]
While upgrading my crate to lyon 1.0, i get errors in my test suite.
For example, trying to parse the path `M 100 300 Q 150 50 250 150 C 250 300 300 300 300 450 A 50 50 0 1 0 450 450 L 550 300` i get `Line 0 Column 75: Expected number, got "".`

To reproduce, with the command line:

``` 
cargo run --bin lyon -- show "M 100 300 Q 150 50 250 150 C 250 300 300 300 300 450 A 50 50 0 1 0 450 450 L 550 300"
```

**Comment by ogoffart** [comment]
Unrelated, but when trying to vary a bit the path to investigate a bit the problem, i can get some panics:

```
cargo run --bin lyon -- show "M 100 300 Q 150 50 250 150 C 250 300 300 300 300 450 A 50 50 0 1 0 450 450 1 1 0 L 550 300"
thread 'main' panicked at 'assertion failed: !arc.is_straight_line()', /home/rust/crates/lyon/crates/geom/src/arc.rs:57:9
```

**Comment by nical** [comment]
Thanks for filing these, I'll have a look soon.
