### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by jcornaz** [nical/lyon#798]
Hi,

I see the [latest version release note](https://github.com/nical/lyon/releases/tag/1.0.0) is: "Remove the changelog file.".

Is there a way/place where we can read the list of changes, especially breaking ones?

**Comment by nical** [comment]
Hi, there is no manually maintained changelog. You can browse through [the commits](https://github.com/nical/lyon/commits/master) on the master branch until you find one that has `version 0.17.` in the name, most of the important changes are briefly diescribed in the [latest blog post](https://nical.github.io/posts/lyon-1-0.html).
