### ISSUE TITLE
Implement finding the intersections between two quadratic bezier curves 

### ISSUE THREAD

**Issue by nical** [nical/lyon#8]
Given two y-monotone quadratic bezier curves, the function should return up to three intersections. 

```
pub enum QuadraticBezierInteresction { None, One(f32), Two(f32, f32), Three(f32, f32, f32) };
pub fn monotone_quadratic_bezier_intersection(a: &QuadraticBezierSegment, b: &QuadraticBezierSegment) -> QuadraticBezierIntersection { ... }
```

In our case the curves are y-monotone (the control point's y coordinate is between the start and end points y coordinates, and the curve can be expressed as a function of y) which may simplify the problem.

**Comment by o0Ignition0o** [comment]
I would probably create a "contains" method for the QuadraticBezierSegment impl :
`pub fn segment_contains_point(&self, p: Point) -> bool {...} `
 which would invoke "flattened_for_each" ... but doing so would be O(n²) if I'm correct.
Any hints / tips on this one ? 
I think I don't understand your last sentence, which is probably why I cannot think of a better way to do this.

**Comment by nical** [comment]
Computing the intersection of two quadratic bezier curves is trickier than I thought it would be when I filed this issue. I mentioned that in our case we can consider the curves y-monotone, this means that for any x value, there is only one y on the curve. This is not actually true of  all of quadratic bezier curves, but it is a simplifying assumption that holds for the particular use case that we have in lyon.
So I thought that it would be easy to express the `x = f(y)` equation of the curve under these constraints and then find x and y by solving analytically the equation `x = f1(y) and x = f2(y)`. As it turns out the underlying math is more complicated than I thought (granted I am no math genius). If you are up for a math challenge you can look into figuring out the solution this way.

Another approach (the only one I've seen implemented when I looked around), is to proceed by recursive subdivision of the curve and take advantage of the fact that a quadratic bezier curve segment is contained into the triangle that is formed by its 3 control points. If two quadratic bezier segments intersect, then their two "bounding" triangles intersect (and testing for intersections between triangles is a lot easier).
If the triangles of the two curves intersect, then subdivide the two curves and do the triangle intersection tests again until either
* there is no intersection
* we subdivided enough that the overlapping pieces of the two curves are very small and flat, and can be approximated with line segments. At this point you can compute the intersection, and then figure out the value of `t1` and `t2` at the intersection point in the equation of the two curves.

**Comment by o0Ignition0o** [comment]
Ok, I've just found https://pomax.github.io/bezierinfo/ I'll read it all and try to tackle this if I'm able to :)

**Comment by nical** [comment]
There is also the approach implemented in pathfinder: https://github.com/pcwalton/pathfinder/blob/master/path-utils/src/intersection.rs
