### ISSUE TITLE
a maybe mistake 

### ISSUE THREAD

**Issue by YoshieraHuang** [nical/lyon#810]
When I read the source code , I find a maybe mistake here:
https://github.com/nical/lyon/blob/cefb67983eedeecd1e54c78d87fd638dedc0c126/crates/tessellation/src/fill.rs#L1330-L1336
This statement means to calculate the x coordinate of a point on an edge. Line 1331 and 1333 do return the x coordinate but Line 1335 return the y coordinate.

**Comment by nical** [comment]
Ouch! Nice catch! indeed it should be `active_edge.to.x`. Do you want to submit the PR for the fix?
