### ISSUE TITLE
Const FillOptions and StrokeOptions

### ISSUE THREAD

**Issue by wrnrlr** [nical/lyon#816]
Is it worth having the `StrokeOptions::with_line_width` declared as a const function so we can use these as const values? Maybe I don't understand the wisdom of the `non_exhaustive` annotation.

**Comment by nical** [comment]
`non_exhaustive` was to let me add fields to the structure without requiring a semver breaking change.
Making the Stroke/FillOption functions const sounds good to me.

**Comment by wrnrlr** [comment]
I've added it everywhere except for `with_miter_limit` because rust does not allow for floating point arithmetic in cost expressions for this is different depending on the hardware.
