### ISSUE TITLE
stateless tessellators

### ISSUE THREAD

**Issue by LU15W1R7H** [nical/lyon#818]
Is it possible to make the tessellators stateless?

Why do we need a `FillTessellator` and `StrokeTessellator` struct in the first place? All relevant information is passed to the `tessellate` functions. It's kind of awkward to have a global tessellator variable or to reconstruct the tessellator for every tessellation.

**Comment by nical** [comment]
The tessellator structs are there to preserve and reuse memory allocations. It has a big impact on performance but if in your case performance is not concern, you can wrap them in simple state-less functions that re-create the tessellators each time.

**Comment by LU15W1R7H** [comment]
Ahh, I see. It affects performance.
