### ISSUE TITLE
Assert with stroke tessellator

### ISSUE THREAD

**Issue by scoopr** [nical/lyon#819]
I happened to encounter a `debug_assert` with stroke tessellator. I managed to minimise it to this,
in wgpu example `main.rs`, 
1. set the stroke tessellator tolerance to `0.1`(the normal default) 
2. replace
```rust
build_logo_path(&mut builder);
```
with
```rust
builder.move_to(point(650.539978027344, 173.559997558594));
builder.line_to(point(650.609985351562, 173.529998779297));
builder.line_to(point(650.729980468750, 173.630004882812));
builder.line_to(point(650.559997558594, 173.570007324219));
builder.close();
```

I couldn't reduce it further, even the last close seems important.
The workaround is easy, by just adjusting tolerance, or even removing the close, so it is not super critical, but panic from debug_assert did surprise me.

**Comment by nical** [comment]
Thanks for filing this and providing a reduced testcase, I'll look into it soon.

**Comment by LU15W1R7H** [comment]
I also a debug_assert in my drawing program. I assume it the same one. It's a bad triangle because some vertices are apparently the same points.
