### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by atouchet** [nical/lyon#834]
The Readme states that lyon is optionally licensed as Mozilla Public License 2.0 while the Cargo.toml file only lists MIT/Apache-2.0. Is one of these incorrect?

**Comment by nical** [comment]
I wanted to reserve the right to license future versions of lyon with MPL2 only. I don't know if I'll ever do that, but it shouldn't matter until then since the MIT/Apache-2.0 combo is strictly more permissive, so in practice, current versions of lyon can be considered as MIT/Apache-2.0.
