### ISSUE TITLE
The folded join workaround sometimes causes miter joins to be clipped

### ISSUE THREAD

**Issue by andrewvarga** [nical/lyon#838]
I have an example path created in Figma that looks like this:
<img width="455" alt="Screenshot 2022-11-08 at 0 18 47" src="https://user-images.githubusercontent.com/911440/200436076-0ca85f80-6bec-4a44-bdd1-e02c2cfdd975.png">

It has 3 points, the middle one has no smoothing but the first and last ones do.
Building that shape in lyon using the `StrokeTesselator` I'm getting results like this:
<img width="229" alt="Screenshot 2022-11-08 at 0 18 58" src="https://user-images.githubusercontent.com/911440/200436234-abc6d35e-610b-4d2b-b285-13bb48b2c0f5.png">

`lineJoin` is set to `LineJoin::Miter` and I played with various miter_limits but seems like it has no effect, MiterClip doesn't seem to work either.
If I move the middle point a bit further down the miter join starts to show up..
I wonder is this expected behaviour or maybe a bug?

The svg in case it's useful is here:
```html
<svg width="352" height="327" viewBox="0 0 352 327" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M16 298C24 148 222 21 222 21C222 21 359 178 332 324" stroke="black" stroke-width="32"/>
</svg>
```

**Comment by andrewvarga** [comment]
Found an easier example with no smooth points at all:
<img width="472" alt="Screenshot 2022-11-08 at 0 31 00" src="https://user-images.githubusercontent.com/911440/200437553-f3b1cd34-3006-464e-aaba-df8c02831d78.png">


It seems if the angle is < 90 deg the miter join just doesn't work:
<img width="253" alt="Screenshot 2022-11-08 at 0 32 10" src="https://user-images.githubusercontent.com/911440/200437637-d3b982ac-e1fb-4816-8625-4d0d3a3e27b0.png">

**Comment by andrewvarga** [comment]
Thanks, I tried playing around with that but with no luck..
Does this look ok?
```rust
    let options = StrokeOptions::default()
        .with_line_width(30.0)
        .with_line_join(LineJoin::Miter)
        .with_miter_limit(99999999999.0);
```

Even with such high miter_limit I can't get the miter to show when the incoming path segment has a control point, even if that control point lies on the same line (so it doesn't really bend the segment):
![Screenshot 2022-11-08 at 10 34 53](https://user-images.githubusercontent.com/911440/200529263-584fcc40-50ff-4901-a289-6810bfa72a2e.png)

this is what I'm seeing after tesselation using lyon:
<img width="264" alt="Screenshot 2022-11-08 at 10 36 15" src="https://user-images.githubusercontent.com/911440/200529307-68122b2d-5a97-4df0-b139-7712c253d702.png">


However if I remove the control point (making the first line segment be a "move_to" instead of `cubic_bezier_to`:
![Screenshot 2022-11-08 at 10 39 08](https://user-images.githubusercontent.com/911440/200529926-7e0ea43b-4f7a-4e0e-ac3a-3468de45a7d6.png)
then I'm getting the expected result using lyon:
<img width="223" alt="Screenshot 2022-11-08 at 10 39 39" src="https://user-images.githubusercontent.com/911440/200529981-e456caef-8b04-4b88-a9a2-200ae6d8fd01.png">

Is there something I can send to make the debugging of this easier? I'm using the `StrokeTessellator's builder`.

**Comment by nical** [comment]
Interesting. An easy way to play around and provide a test case for me to reproduce is to use the cli tool in the reporistory. For example got to the cli folder and run:

```
cargo run -- show "M16 298C24 148 222 21 222 21C222 21 359 178 332 324" -s -w 32 --line-join Miter --miter-limit 100
```

You can move around in the viewer using the arrow keys and zoom in/out with page-up and page-down.

The command above shows the path from your first example. Interestingly the join isn't clipped when I run it. If for some reason the issue never reproduces on the cli tool it'll be somewhat surprising but should at least narrow down the space of potential issues.

**Comment by andrewvarga** [comment]
I could find an example that I think reproduces what I was referring to:
```
cargo run -- show "M24.948 291.149C84.4693 215.841 235.225 55.5598 235.225 55.5598C235.225 55.5598 342.906 293.062 320.424 372.895" -s -w 32 --line-join Miter --miter-limit 99999999
```
What I'm getting is:
![Screenshot 2022-11-08 at 17 04 23](https://user-images.githubusercontent.com/911440/200615317-f4158e6d-865d-4851-8046-e21d9c902fe7.png)

Can't really seem to find a `miter-limit` value that doesn't clip the join.
Here's what the shape looks like in Figma (first and last points have a control point, middle point doesn't have any):

<img width="159" alt="Screenshot 2022-11-08 at 17 05 59" src="https://user-images.githubusercontent.com/911440/200615788-e55595bc-b714-4df1-b95e-62ba6986bb86.png">

**Comment by nical** [comment]
Ah, I think I see what's going on here. It's not a straightforward thing to fix but it's not insurmountable. I'll look into a fix when I have a bit of spare time to wrap my head around it, hopefully soon-ish.

**Comment by andrewvarga** [comment]
> Ah, I think I see what's going on here. It's not a straightforward thing to fix but it's not insurmountable. I'll look into a fix when I have a bit of spare time to wrap my head around it, hopefully soon-ish.

Great, thank you so much! And let me know if I can help, obviously I'm not familiar with the codebase but happy to be involved.

**Comment by andrewvarga** [comment]
Thanks for the fix! I'll check this out once the new release comes out!

**Comment by nical** [comment]
It's up in lyon_tessellation 1.0.6

**Comment by andrewvarga** [comment]
> It's up in lyon_tessellation 1.0.6

Thank you, tested out, it all seems to work now!
