### ISSUE TITLE
wgpu_svg example: PrimitiveTopology vs PolygonMode

### ISSUE THREAD

**Issue by sgentle** [nical/lyon#840]
Hi! I came across this comment while I was checking out the wgpu_svg example:
https://github.com/nical/lyon/blob/7487d32939d32160554dbd8a7217437334f9c4b2/examples/wgpu_svg/src/main.rs#L390-L392

I think `render_pipeline_descriptor.primitive.polygon_mode = wgpu::PolygonMode::Line;` might be what you're looking for. I haven't tested it (I'm just using the example as reference for an OpenGL SVG renderer), but the docs seem to line up at least.

**Comment by nical** [comment]
Indeed, thanks for pointing it out. The example predates the addition of this feature to wgpu, but it's nice to see it's now available in most places.
