### ISSUE TITLE
Rounded Polygons

### ISSUE THREAD

**Issue by wainwrightmark** [nical/lyon#846]
It would be nice to have an easy way to create polygons with rounded corners.  
The interface would be similar to that of `Polygon` but would have additional parameters for corner radius and whether the points are specified in clockwise or anticlockwise order.

I've managed to build a rudimentary version of this for my project, I'm happy to expand and contribute it if you think it's a good feature.

**Comment by nical** [comment]
The builders for the default path data structure have a helper for that: https://docs.rs/lyon_path/latest/lyon_path/builder/struct.NoAttributes.html#method.add_rounded_rectangle is it what you are looking for?

**Comment by wainwrightmark** [comment]
I'm looking for the same visual effect as that but for arbitrary polygons (both convex and concave), similar to https://docs.rs/lyon_path/latest/lyon_path/builder/struct.NoAttributes.html#method.add_polygon

**Comment by nical** [comment]
Oh right, sorry, I read your original message a tad too quickly. If your implementation is general enough to work as expected for all polygons, we could add it to lyon_algorithms.
It should probably be implemented as a function that takes a `Polygon` and a `&mut PathBuilder` as parameters.
