### ISSUE TITLE
Miter limit inconsistent with other SVG renderers

### ISSUE THREAD

**Issue by antonok-edm** [nical/lyon#847]
I encountered a path with a miter join that is unclipped in Inkscape, Chromium, and Firefox, but clipped when rendered by `lyon`.

Here's the relevant path in `lyon`'s CLI renderer:

`cargo run -- show "m 5,9 c 0,-3 6,-4 6,-2 1,0 1,1 2,3 C 14,6 20,6 20,9 20,23 5,19 5,9 Z" -s -w .4 --line-join Miter --miter-limit 4 -t 0.01`

And here's a corresponding SVG with the same path, miter limit, and line width:

![min](https://user-images.githubusercontent.com/22821309/210154270-e317c1a6-e6db-49c4-9f4e-24b0c2412202.svg)

It's small, but it's quite visible when zooming in.

`lyon` switches to rendering the miter join unclipped somewhere between `--miter-limit 5.5` and `--miter-limit 5.505`, although that's significantly higher than any of the other SVG renderers.

**Comment by nical** [comment]
Hi, thanks for filing this and providing a test case. Turns out the miter-limit test was implemented incorrectly (it didn't take the stroke width into account).
I'll put up a fix soon.
