### ISSUE TITLE
PathMeasurements crashes with a path length of 0

### ISSUE THREAD

**Issue by felixfaire** [nical/lyon#853]
Trying to create a PathMeasurements using PathMeasurements::from_path(path) causes an out of bounds error when the path length is 0.

I would consider a Path made of a single point still a legitimate path and as such should probably not crash when measured.

**Comment by nical** [comment]
Oops! Thanks for filing this, I'll look into it soon.

**Comment by felixfaire** [comment]
Amazing, thanks for the swift response.
