### ISSUE TITLE
API guidelines: methods on collections that produce iterators follow the iter, iter_mut, into_iter conventions.

### ISSUE THREAD

**Issue by nical** [nical/lyon#86]
This is a sub-issue for #44.

We should audit the docs/code of each lyon crate and check that [Methods on collections that produce iterators follow `iter`, `iter_mut`, `into_iter`](https://github.com/brson/rust-api-guidelines#c-iter).
If some of the code happens to not follow the guidelines we should fix it.

**Comment by OfficialURL** [comment]
I believe `clippy` can automatically catch these kinds of errors. If so, I can confirm that there aren't any (and if there were, they would be closed by #664).

**Comment by nical** [comment]
Cool thanks!
