### ISSUE TITLE
Help a noob draw a circle on the GPU

### ISSUE THREAD

**Issue by vvzen** [nical/lyon#874]
Hi!

First of all, thanks for this very useful and inspiring library. I have the utmost respect for people that allow other people to push nicer pixels on the GPU thanks to their work!

I am having some troubles trying to understand how to draw a circle using wgpu, I was wondering was exactly could be the problem, since I know that "I'm holding it wrong" :)
As somebody that has just recently started playing around with GPU programming, I basically "don't know what I don't know", so it gets a bit hard to debug my own issues.

TL;DR: I am using lyon to generate a circle that I want to draw via wgpu, but this is what I'm getting right now:

![lyon_circle_MRE](https://github.com/nical/lyon/assets/10340139/630bbc59-4305-4356-aa57-f2050b806e87)

The core of the code is basically this:
```rust
// Vertices + Indices
type TessellatedOutput = (Vec<Vertex>, Vec<u16>);

#[repr(C)]
#[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 3],
    color: [f32; 3],
}

fn generate_circle(center_xy: (f32, f32), radius: f32, color: &Color) -> TessellatedOutput {
    let mut geometry: VertexBuffers<Vertex, u16> = VertexBuffers::new();

    let mut tessellator = FillTessellator::new();
    let options = FillOptions::default().with_tolerance(0.001);

    tessellator
        .tessellate_circle(
            point(center_xy.0, center_xy.1),
            radius,
            &options,
            &mut BuffersBuilder::new(&mut geometry, |vertex: FillVertex| {
                let p = vertex.position().to_3d();
                let c = color.clone().as_array();
                Vertex {
                    position: p.into(),
                    color: c,
                }
            }),
        )
        .unwrap();

    eprintln!(
        "-- Circle: {} vertices {} indices",
        geometry.vertices.len(),
        geometry.indices.len()
    );

    (geometry.vertices.to_vec(), geometry.indices.to_vec())
}
```

but I have a full repro here: https://github.com/vvzen/lyon-mre

Is there anything blaringly wrong in how I am generating the circle vertices/indices? 

In case it helps, my wgpu topology is:
```rust
wgpu::PrimitiveTopology::TriangleStrip;
```

and my primitive state is:
```rust
        primitive: wgpu::PrimitiveState {
            topology,
            strip_index_format: Some(wgpu::IndexFormat::Uint16),
            front_face: wgpu::FrontFace::Ccw,
            cull_mode: Some(wgpu::Face::Back),
            polygon_mode: wgpu::PolygonMode::Fill,
            unclipped_depth: false,
            conservative: false,
        },
```

Thanks!

**Comment by vvzen** [comment]
Nevermind, I figured it out! Of course, I was holding it wrong.
I more closely followed the tutorial here: https://docs.rs/lyon_tessellation/latest/lyon_tessellation/geometry_builder/index.html#generating-custom-vertices and now thing are being drawn as expected!

![it_works](https://github.com/nical/lyon/assets/10340139/87d37673-75a1-4886-9ce9-f7fe4c3a742b)

In case it helps somebody, the diff is available here:
- https://github.com/vvzen/lyon-mre/pull/1/files
- https://github.com/vvzen/lyon-mre/pull/1/commits/48175fea65b5006744e9da6d0371a8f975c7954d

**Comment by nical** [comment]
I'm a bit late to the party, glad you found what was going wrong!
