### ISSUE TITLE
Using custom vertex attributes with rounded rectangles.

### ISSUE THREAD

**Issue by therocode** [nical/lyon#875]
It seems like we can use custom vertex attributes to add things like UV to the outputted geometry and this is great. However it seems to me like the `add_rounded_rectangle()` API does not work with these since it works off the simple builder which doesn't seem to expose such.

Is there a way I'm not seeing that means I can use pre-made ways to create a rounded rectangle and get UV on the result using custom vertex attributes, without having to trace the path entirely manually?

**Comment by nical** [comment]
You could do some math in the geometry builder: Figure out the transformation between the vertex position and and the uvs and apply it there. For example, say you have a rounded rectangle with bounds `rect` mapping to bounds `uv_rect` in the texture.
The formula should be something along the lines of: 

```
let t = (vertex.position() - rect.min) / rect.size();
uv = uv_rect.min + uv_rect.size() * t;
```

This only deals with scale+offset but you can generalize it to more arbitrary transformations depending on your needs.

**Comment by therocode** [comment]
Oh, yeah that works and should be easy for any produced shape that is derived from a rectangle, like the rounded rectangle. Thanks for that 👌

**Comment by nical** [comment]
My pleasure! I'll close this since it looks like you are satisfied with the resolution.
