### ISSUE TITLE
debug_assert can panic while not being necessarily justififed

### ISSUE THREAD

**Issue by twiby** [nical/lyon#885]
There a `debug_assert` that can fail in `tessellation/src/monotone.rs` at line 115. 
My use case is a drawing app built partly using `lyon` (it's called Rayon, at www.rayon.design), and I'm not 100% sure how this is triggered, but while not in debug mode, everything seem completely fine, though in debug mode, in a specific case, this panics. I wonder if this `debug_assert` is absolutely necessary !

Anyway, if it actually is, please ignore this issue, but I thought I'd point that out (it is a small annoyance for me when debugging)

**Comment by nical** [comment]
Hi, that assertion is unfortunately subject to floating point precision hazards. It has a generous, but apparently not big enough, threshold. I'll remove it.
