### ISSUE TITLE
Tesselator doesn't handle intersections between different paths very well

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [nical/lyon#888]
simplest example: a hexagram
it tesselates incorrectly

**Comment by nical** [comment]
Hi, could you provide a test case that shows the issue you are seeing?

**Comment by H-A-M-G-E-R** [comment]
how to provide a test case

**Comment by H-A-M-G-E-R** [comment]
and also how to run it

**Comment by nical** [comment]
One way could be to use the cli tool with an SVG path that reproduces the issue.
In the `cli` folder of this repository there is a tool that you can use to try out the tessellator, giving it a single path in the SVG path data syntax.

For example:

```bash
# in the cli folder
cargo run show "M 0 50 L 100 50 50 150 Z M 0 130 100 130 50 20 Z" --fill-rule nonzero
```

correctly renders an hexagram looking thing. You can replace the `nonzero` fill rule with `evenodd` depending on which behavior you need to test.

Or you could modify one of the examples until it reproduces your issue and paste here code of the modified example.
