### ISSUE TITLE
Lifetime issue when storing Tesselator::builder() in a struct and later resetting it

### ISSUE THREAD

**Issue by qmathe** [nical/lyon#892]
Hi,

I'm writing a Rust library based on Lyon for a macOS app written in Swift. I'd like to store [FillTesselator::builder()](https://docs.rs/lyon_tessellation/latest/lyon_tessellation/struct.FillTessellator.html#method.builder) in a `Renderer` struct, use it across multiple methods and reset it every time a path is finished. The goal is to expose this Renderer as a C API and call it from Swift. The foreign code would be responsible to create the renderer too. I copied/pasted a simplified version of the code at the end.

Even if I use `Rc` and `RefCell`, I cannot figure out how to make this code compiles due to `Renderer::begin_compound_path()` breaking *'a* lifetime when resetting all tesselator related state.

There are two solutions I'm considering currently:
- create all the tesselator state outside of the `Renderer` and pass it to `Renderer::new()`
- create an intermediate path with a `PathBuilder`, then scope the creation and use of the tesselator to  `Renderer::end_compound_path()`

Do you see a better way to work around this lifetime issue or am I misusing Lyon API?

```rust
pub struct Renderer<'a> {
    tess: Option<NoAttributes<FillBuilder<'a>>,
    buffers: VertexBuffers<Point2D<f32, UnknownUnit>, u16>,
    vertex_builder: Option<SimpleBuffersBuilder<'a>>,
    fill: Option<FillTessellator>,
    options: FillOptions,
    results: Vec<TesselationResult>
}

impl<'a> Renderer<'a> {

    pub fn new() -> Renderer<'a> {
        Renderer {
            tess: Non),
            buffers: VertexBuffers::new(),
            vertex_builder: None,
            fill: None,
            options: FillOptions::default(),
            results: vec![]
         }
    }

    pub fn begin_compound_path(&mut self) {
        self.buffers.indices.clear();
        self.buffers.vertices.clear();
        self.vertex_builder.replace(Some(simple_builder(&mut self.buffers)));
        self.fill = Some(FillTessellator::new());
        self.tess = Some(self.fill.as_mut().unwrap().builder(
            &self.options,
            self.vertex_builder.as_mut().unwrap()
        ));
        self.results.clear();
    }

    pub fn end_compound_path(&mut self) {
        results.push(tess.build());
    }

    pub fn begin(&mut self, at: Point) {
        self.tess.as_mut().unwrap().begin(at);
    }

    pub fn line(&mut self, to: Point) {
        self.tess.as_mut().unwrap().line(to);
    }

    pub fn end(&mut self, close: bool) {
        self.tess.as_mut().unwrap().end(close);
    }
}
```

**Comment by qmathe** [comment]
Thanks for your reply! Yes, I was trying to avoid creating paths. Currently I have a single-thread CPU renderer where I can support rendering 10 000 paths without performance issues. I want to move to a GPU renderer to support rendering 50 000 to 100 000 paths. 

On the Swift side, I have already a Path object and I iterate on path segments to render them. For each path segment, with the CPU renderer, I call a corresponding CoreGraphics function to draw it.  So I was hoping to keep the same model with a renderer based on WebGPU + Lyon and avoid passing complex objects through the C interface.

What do you mean by _having path objects in your API is that you can lean on that to do some caching internally_? For caching tessellated paths, my plan is to pass an ID and a version to `begin_compound_path()`, then cache the geometry result output by the tessellator  for this (ID, version) pair. The ID and version would come from the Path object I maintain on the Swift side. Should I take another approach?

**Comment by nical** [comment]
> What do you mean by having path objects in your API is that you can lean on that to do some caching internally? 

I was referring to APIS that have retained path objects so rendering them look like `canvas.fill(path)` as opposed to passing path commands directly on the canvas like:

```rust 
canvas.move_to(a);
canvas.line_to(b);
//etc.
canvas.fill();
```

But you already have path objects on the swift side and some scheme for avoiding to tessellate the same paths each frame which sounds good.

So I think that this is more of a rust question that a lyon question. Your usage of lyon looks fine to me, but rust isn't happy about how your renderer struct references itself by having the contents of `vertex_builder` point to `buffers`. Trying to split out the state as you said in your initial comment would probably help.

**Comment by qmathe** [comment]
ok, I get what you mean now by having path objects in the API.

Thanks a lot for your feedback, that was insightful. I agree it's more question about how I use Rust, but I wasn't sure initially. For now, I'll start with creating intermediate path objects and take another look later to eliminate them, if they happen to impact performance.
