### ISSUE TITLE
Is there an example of using custom attributes?

### ISSUE THREAD

**Issue by schell** [nical/lyon#906]
First off - thanks for your library! It's super cool. 

I'd like to be able to build paths that change color. I think I can do this with custom attributes, but I don't see any documentation or example about them. Maybe I'm just missing some?

**Comment by nical** [comment]
Hi, thanks for the kind words.

There isn't. In a nutshell, you can create paths with, say, 4 custom attributes (it will add 4 floats per endpoint) by creating a path builder using `let mut  builder = Path::builder_with_attributes(4)`, then endpoints which usually takes a `Point` position take a `&[f32]` slice to specify the attributes. For example `builder.quadratic_bezier_to(ctrl, to, &[0.5, 0.5, 0.5, 1.0])`.

If you want to use them with the tessellators, implement your own vertex builder and access the custom attributes using  for example [FillVertex::interpolated_attributes()](https://docs.rs/lyon_tessellation/latest/lyon_tessellation/struct.FillVertex.html#method.interpolated_attributes).

**Comment by schell** [comment]
Great! Thank you @nical.
