### ISSUE TITLE
`end_cap` seems to have no effect if its `LineCap::Square`

### ISSUE THREAD

**Issue by TheNeikos** [nical/lyon#907]
I am using lyon through `bevy_prototype_lyon` and it exposes the `StrokeOptions` struct. However setting `end_cap` has no effect on the tesselated result.

Going through the source code, it seems that the handling of the end_cap is simply missing for anything except round? I do not know the code well enough to suggest a PR myself however (and could be totally wrong here)

https://github.com/nical/lyon/blob/3c709ff5f263897447da9ed8fd153614728cf356/crates/tessellation/src/stroke.rs#L2162-L2176

**Comment by nical** [comment]
Thanks for filing this. Indeed the handling of Square end caps is missing for some reason.
